In [3]:
# use simple model and simulate data to test the code
import tensorflow as tf
import numpy as np
from tensorflow import keras
from tensorflow.keras import layers
from tensorflow.keras import initializers
from tensorflow.keras import Model
from tensorflow.keras.layers import Flatten, Dense

In [2]:
# simulate data
initializer = initializers.RandomUniform(minval=-2., maxval=2.)
model_sil = keras.Sequential(
    [
        keras.Input(shape=(5,)),
        layers.Dense(5, activation='tanh'),
        #layers.Dense(10, activation="sigmoid", kernel_initializer='glorot_uniform'),
        layers.Dense(5, activation='tanh'),
        #layers.Dense(1000, activation="sigmoid", kernel_initializer='glorot_uniform'),
        layers.Dense(1, activation="sigmoid", kernel_initializer='glorot_uniform')
    ]
)

model_sil.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 5)                 30        
_________________________________________________________________
dense_1 (Dense)              (None, 5)                 30        
_________________________________________________________________
dense_2 (Dense)              (None, 1)                 6         
Total params: 66
Trainable params: 66
Non-trainable params: 0
_________________________________________________________________


In [3]:
model_sil.get_weights()

[array([[-0.03181505, -0.29496625, -0.1826523 , -0.17110789, -0.1290273 ],
        [ 0.49242675, -0.50602317, -0.2874465 ,  0.22966921,  0.61879694],
        [ 0.03926867,  0.05115497,  0.3630613 , -0.3642165 ,  0.42776704],
        [-0.38435218,  0.62644947,  0.34494114, -0.6458128 ,  0.52241397],
        [-0.04669535, -0.5371206 ,  0.14296389, -0.62401265,  0.38713145]],
       dtype=float32),
 array([0., 0., 0., 0., 0.], dtype=float32),
 array([[-0.72497624, -0.61719006, -0.2052536 , -0.5281552 , -0.4796866 ],
        [-0.05740094,  0.03633362, -0.6047278 ,  0.5440091 , -0.27685797],
        [ 0.7310597 ,  0.35987294, -0.20840847,  0.77059567,  0.40918422],
        [-0.02991992,  0.39067626, -0.17683142, -0.01015508,  0.10029674],
        [ 0.30753672, -0.6691123 ,  0.23325694, -0.41835976, -0.27896333]],
       dtype=float32),
 array([0., 0., 0., 0., 0.], dtype=float32),
 array([[-0.29849648],
        [-0.69295573],
        [ 0.52453494],
        [ 0.42195272],
        [ 0.4160397 

In [6]:
import random
random.seed(1234)
x_train = np.random.randn(10, 5)
print(x_train)

y_cont = model_sil.predict(x_train)
y = (y_cont > 0.5).astype("int32")
print(y)
#print(np.unique(y, return_counts=True))

[[-0.2005539   0.53977676  1.15897269 -1.08190609 -0.73337221]
 [-0.17033051 -1.23041316 -0.11680444  0.49305817 -0.65803933]
 [-0.36680738 -0.42298462  0.55971521  1.36372174 -0.42587423]
 [ 0.2418414  -0.28214645 -0.18894039  0.74359321 -0.91053086]
 [-0.59242727 -0.43759613  0.53355006 -0.18793894 -0.75499497]
 [ 1.22662592 -0.53538284  0.69556242 -1.73187526  1.37258738]
 [ 0.53306775  0.80922895  0.94110106 -1.23331496 -2.79451847]
 [-2.49602801 -0.43566325 -1.98261163  1.42694895 -0.20047027]
 [-0.01825811  0.872897    0.23697962  0.05049487 -0.76889097]
 [ 0.61064762  1.19946725 -1.25929003 -0.41979978 -1.79907538]]


NameError: name 'model_sil' is not defined

In [7]:
with open('testdata.npy','wb') as f:
    np.save(f, x_train)
    np.save(f, y_train)

In [9]:
with open('testdata.npy','rb') as f:
    x = np.load(f)
    y = np.load(f)

In [10]:
print(np.unique(y, return_counts=True))

(array([0, 1], dtype=int32), array([268, 232]))


In [11]:
# test BP for the data
model = keras.Sequential(
    [
        keras.Input(shape=(5,)),
        layers.Dense(5, activation='sigmoid'),
        layers.Dense(5, activation='sigmoid'),
        layers.Dense(1, activation='sigmoid')
    ]
)

In [14]:
batch_size = 32
epochs = 50

#model.compile(loss="sparse_categorical_crossentropy", optimizer="adam", metrics=["accuracy"])
model.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])
model.fit(x_train, y_train, batch_size=batch_size, epochs=epochs)

Epoch 1/50
16/16 [==============================] - 0s 1ms/step - loss: 0.2224 - accuracy: 0.9740
Epoch 2/50
16/16 [==============================] - 0s 2ms/step - loss: 0.2167 - accuracy: 0.9740
Epoch 3/50
16/16 [==============================] - 0s 2ms/step - loss: 0.2115 - accuracy: 0.9720
Epoch 4/50
16/16 [==============================] - 0s 2ms/step - loss: 0.2065 - accuracy: 0.9720
Epoch 5/50
16/16 [==============================] - 0s 2ms/step - loss: 0.2016 - accuracy: 0.9720
Epoch 6/50
16/16 [==============================] - 0s 2ms/step - loss: 0.1969 - accuracy: 0.9700
Epoch 7/50
16/16 [==============================] - 0s 2ms/step - loss: 0.1927 - accuracy: 0.9700
Epoch 8/50
16/16 [==============================] - 0s 2ms/step - loss: 0.1882 - accuracy: 0.9700
Epoch 9/50
16/16 [==============================] - 0s 2ms/step - loss: 0.1841 - accuracy: 0.9700
Epoch 10/50
16/16 [==============================] - 0s 2ms/step - loss: 0.1803 - accuracy: 0.9700
Epoch 11/50
16/16 [