In [1]:
# Use exclusive OR to test the MH_MLP code
import tensorflow as tf
import tensorflow_probability as tfp
import numpy as np
import random
from tensorflow import keras
from tensorflow.keras import layers
from tensorflow.keras import initializers
from tensorflow.keras import Model
from tensorflow.keras.layers import Flatten, Dense
from sklearn.metrics import accuracy_score

In [2]:
# Set data
x_train = np.array([[0, 0],
           [0, 1],
           [1, 0],
           [1, 1]])
y_train = np.array([[0],
           [1],
           [1],
           [0]])
print(x_train)
print(y_train)

[[0 0]
 [0 1]
 [1 0]
 [1 1]]
[[0]
 [1]
 [1]
 [0]]


In [4]:
# Standard BP
model_bp = keras.Sequential(
    [
        keras.Input(shape=(2,)),
        layers.Dense(2, activation = "sigmoid"),
        layers.Dense(1, activation = "sigmoid")
    ]
)
model_bp.summary()
model_bp.get_weights()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 2)                 6         
_________________________________________________________________
dense_1 (Dense)              (None, 1)                 3         
Total params: 9
Trainable params: 9
Non-trainable params: 0
_________________________________________________________________


[array([[0.15866828, 1.2130369 ],
        [1.2147189 , 0.8022579 ]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[-0.93405545],
        [ 0.10520828]], dtype=float32),
 array([0.], dtype=float32)]

In [5]:
# Set weight
w_0 = np.array([[1, -1], [1, -1]], dtype = "float32")
b_0 = np.array([-0.5, 1], dtype = "float32")
l_0 = [w_0, b_0]

w_1 = np.array([[1], [1]], dtype = "float32")
b_1 = np.array([-1], dtype = "float32")
l_1 = [w_1, b_1]

model_bp.layers[0].set_weights(l_0)
model_bp.layers[1].set_weights(l_1)
model_bp.get_weights()

[array([[ 1., -1.],
        [ 1., -1.]], dtype=float32),
 array([-0.5,  1. ], dtype=float32),
 array([[1.],
        [1.]], dtype=float32),
 array([-1.], dtype=float32)]

In [26]:
batch_size = 4
epochs = 2000
opt = tf.keras.optimizers.SGD(learning_rate=0.1)

model_bp.compile(loss="binary_crossentropy", optimizer=opt, metrics=["accuracy"])
model_bp.fit(x_train, y_train, batch_size=batch_size, epochs=epochs)

Epoch 1/2000
1/1 [==============================] - 0s 1ms/step - loss: 0.6885 - accuracy: 0.5000
Epoch 2/2000
1/1 [==============================] - 0s 3ms/step - loss: 0.6883 - accuracy: 0.5000
Epoch 3/2000
1/1 [==============================] - 0s 1ms/step - loss: 0.6882 - accuracy: 0.5000
Epoch 4/2000
1/1 [==============================] - 0s 1ms/step - loss: 0.6881 - accuracy: 0.5000
Epoch 5/2000
1/1 [==============================] - 0s 1ms/step - loss: 0.6880 - accuracy: 0.5000
Epoch 6/2000
1/1 [==============================] - 0s 1ms/step - loss: 0.6879 - accuracy: 0.5000
Epoch 7/2000
1/1 [==============================] - 0s 1ms/step - loss: 0.6878 - accuracy: 0.5000
Epoch 8/2000
1/1 [==============================] - 0s 1ms/step - loss: 0.6877 - accuracy: 0.5000
Epoch 9/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.6876 - accuracy: 0.5000
Epoch 10/2000
1/1 [==============================] - 0s 3ms/step - loss: 0.6875 - accuracy: 0.5000
Epoch 11/2000
1/1 [

1/1 [==============================] - 0s 1ms/step - loss: 0.6787 - accuracy: 0.7500
Epoch 166/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.6786 - accuracy: 0.7500
Epoch 167/2000
1/1 [==============================] - 0s 1ms/step - loss: 0.6786 - accuracy: 0.7500
Epoch 168/2000
1/1 [==============================] - 0s 4ms/step - loss: 0.6785 - accuracy: 0.7500
Epoch 169/2000
1/1 [==============================] - 0s 3ms/step - loss: 0.6784 - accuracy: 0.7500
Epoch 170/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.6784 - accuracy: 0.7500
Epoch 171/2000
1/1 [==============================] - 0s 1ms/step - loss: 0.6783 - accuracy: 0.7500
Epoch 172/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.6783 - accuracy: 0.7500
Epoch 173/2000
1/1 [==============================] - 0s 1ms/step - loss: 0.6782 - accuracy: 0.7500
Epoch 174/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.6781 - accuracy: 0.7500
Epoch 175/2000


1/1 [==============================] - 0s 2ms/step - loss: 0.6681 - accuracy: 0.7500
Epoch 329/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.6680 - accuracy: 0.7500
Epoch 330/2000
1/1 [==============================] - 0s 3ms/step - loss: 0.6680 - accuracy: 0.7500
Epoch 331/2000
1/1 [==============================] - 0s 1ms/step - loss: 0.6679 - accuracy: 0.7500
Epoch 332/2000
1/1 [==============================] - 0s 3ms/step - loss: 0.6678 - accuracy: 0.7500
Epoch 333/2000
1/1 [==============================] - 0s 6ms/step - loss: 0.6678 - accuracy: 0.7500
Epoch 334/2000
1/1 [==============================] - 0s 1ms/step - loss: 0.6677 - accuracy: 0.7500
Epoch 335/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.6676 - accuracy: 0.7500
Epoch 336/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.6675 - accuracy: 0.7500
Epoch 337/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.6675 - accuracy: 0.7500
Epoch 338/2000


1/1 [==============================] - 0s 3ms/step - loss: 0.6618 - accuracy: 0.7500
Epoch 411/2000
1/1 [==============================] - 0s 3ms/step - loss: 0.6618 - accuracy: 0.7500
Epoch 412/2000
1/1 [==============================] - 0s 1ms/step - loss: 0.6617 - accuracy: 0.7500
Epoch 413/2000
1/1 [==============================] - 0s 1ms/step - loss: 0.6616 - accuracy: 0.7500
Epoch 414/2000
1/1 [==============================] - 0s 1ms/step - loss: 0.6615 - accuracy: 0.7500
Epoch 415/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.6614 - accuracy: 0.7500
Epoch 416/2000
1/1 [==============================] - 0s 5ms/step - loss: 0.6613 - accuracy: 0.7500
Epoch 417/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.6613 - accuracy: 0.7500
Epoch 418/2000
1/1 [==============================] - 0s 7ms/step - loss: 0.6612 - accuracy: 0.7500
Epoch 419/2000
1/1 [==============================] - 0s 4ms/step - loss: 0.6611 - accuracy: 0.7500
Epoch 420/2000


1/1 [==============================] - 0s 9ms/step - loss: 0.6548 - accuracy: 0.7500
Epoch 493/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.6547 - accuracy: 0.7500
Epoch 494/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.6546 - accuracy: 0.7500
Epoch 495/2000
1/1 [==============================] - 0s 1ms/step - loss: 0.6545 - accuracy: 0.7500
Epoch 496/2000
1/1 [==============================] - 0s 1ms/step - loss: 0.6544 - accuracy: 0.7500
Epoch 497/2000
1/1 [==============================] - 0s 5ms/step - loss: 0.6544 - accuracy: 0.7500
Epoch 498/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.6543 - accuracy: 0.7500
Epoch 499/2000
1/1 [==============================] - 0s 1ms/step - loss: 0.6542 - accuracy: 0.7500
Epoch 500/2000
1/1 [==============================] - 0s 1ms/step - loss: 0.6541 - accuracy: 0.7500
Epoch 501/2000
1/1 [==============================] - 0s 1ms/step - loss: 0.6540 - accuracy: 0.7500
Epoch 502/2000


1/1 [==============================] - 0s 2ms/step - loss: 0.6470 - accuracy: 0.7500
Epoch 575/2000
1/1 [==============================] - 0s 4ms/step - loss: 0.6469 - accuracy: 0.7500
Epoch 576/2000
1/1 [==============================] - 0s 1ms/step - loss: 0.6468 - accuracy: 0.7500
Epoch 577/2000
1/1 [==============================] - 0s 1ms/step - loss: 0.6467 - accuracy: 0.7500
Epoch 578/2000
1/1 [==============================] - 0s 3ms/step - loss: 0.6466 - accuracy: 0.7500
Epoch 579/2000
1/1 [==============================] - 0s 5ms/step - loss: 0.6465 - accuracy: 0.7500
Epoch 580/2000
1/1 [==============================] - 0s 6ms/step - loss: 0.6464 - accuracy: 0.7500
Epoch 581/2000
1/1 [==============================] - 0s 1ms/step - loss: 0.6463 - accuracy: 0.7500
Epoch 582/2000
1/1 [==============================] - 0s 3ms/step - loss: 0.6462 - accuracy: 0.7500
Epoch 583/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.6461 - accuracy: 0.7500
Epoch 584/2000


1/1 [==============================] - 0s 5ms/step - loss: 0.6383 - accuracy: 0.7500
Epoch 657/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.6382 - accuracy: 0.7500
Epoch 658/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.6381 - accuracy: 0.7500
Epoch 659/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.6380 - accuracy: 0.7500
Epoch 660/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.6379 - accuracy: 0.7500
Epoch 661/2000
1/1 [==============================] - 0s 3ms/step - loss: 0.6378 - accuracy: 0.7500
Epoch 662/2000
1/1 [==============================] - 0s 1ms/step - loss: 0.6377 - accuracy: 0.7500
Epoch 663/2000
1/1 [==============================] - 0s 4ms/step - loss: 0.6376 - accuracy: 0.7500
Epoch 664/2000
1/1 [==============================] - 0s 1ms/step - loss: 0.6374 - accuracy: 0.7500
Epoch 665/2000
1/1 [==============================] - 0s 1ms/step - loss: 0.6373 - accuracy: 0.7500
Epoch 666/2000


1/1 [==============================] - 0s 1ms/step - loss: 0.6288 - accuracy: 0.7500
Epoch 739/2000
1/1 [==============================] - 0s 1ms/step - loss: 0.6286 - accuracy: 0.7500
Epoch 740/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.6285 - accuracy: 0.7500
Epoch 741/2000
1/1 [==============================] - 0s 3ms/step - loss: 0.6284 - accuracy: 0.7500
Epoch 742/2000
1/1 [==============================] - 0s 6ms/step - loss: 0.6283 - accuracy: 0.7500
Epoch 743/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.6282 - accuracy: 0.7500
Epoch 744/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.6280 - accuracy: 0.7500
Epoch 745/2000
1/1 [==============================] - 0s 7ms/step - loss: 0.6279 - accuracy: 0.7500
Epoch 746/2000
1/1 [==============================] - 0s 1ms/step - loss: 0.6278 - accuracy: 0.7500
Epoch 747/2000
1/1 [==============================] - 0s 4ms/step - loss: 0.6277 - accuracy: 0.7500
Epoch 748/2000


1/1 [==============================] - 0s 2ms/step - loss: 0.6182 - accuracy: 0.7500
Epoch 821/2000
1/1 [==============================] - 0s 5ms/step - loss: 0.6181 - accuracy: 0.7500
Epoch 822/2000
1/1 [==============================] - 0s 1ms/step - loss: 0.6180 - accuracy: 0.7500
Epoch 823/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.6178 - accuracy: 0.7500
Epoch 824/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.6177 - accuracy: 0.7500
Epoch 825/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.6176 - accuracy: 0.7500
Epoch 826/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.6174 - accuracy: 0.7500
Epoch 827/2000
1/1 [==============================] - 0s 7ms/step - loss: 0.6173 - accuracy: 0.7500
Epoch 828/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.6172 - accuracy: 0.7500
Epoch 829/2000
1/1 [==============================] - 0s 3ms/step - loss: 0.6170 - accuracy: 0.7500
Epoch 830/2000


1/1 [==============================] - 0s 4ms/step - loss: 0.6068 - accuracy: 0.7500
Epoch 903/2000
1/1 [==============================] - 0s 9ms/step - loss: 0.6066 - accuracy: 0.7500
Epoch 904/2000
1/1 [==============================] - 0s 4ms/step - loss: 0.6065 - accuracy: 0.7500
Epoch 905/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.6063 - accuracy: 0.7500
Epoch 906/2000
1/1 [==============================] - 0s 4ms/step - loss: 0.6062 - accuracy: 0.7500
Epoch 907/2000
1/1 [==============================] - 0s 4ms/step - loss: 0.6060 - accuracy: 0.7500
Epoch 908/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.6059 - accuracy: 0.7500
Epoch 909/2000
1/1 [==============================] - 0s 1ms/step - loss: 0.6057 - accuracy: 0.7500
Epoch 910/2000
1/1 [==============================] - 0s 1ms/step - loss: 0.6056 - accuracy: 0.7500
Epoch 911/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.6055 - accuracy: 0.7500
Epoch 912/2000


1/1 [==============================] - 0s 2ms/step - loss: 0.5944 - accuracy: 0.7500
Epoch 985/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.5942 - accuracy: 0.7500
Epoch 986/2000
1/1 [==============================] - 0s 4ms/step - loss: 0.5941 - accuracy: 0.7500
Epoch 987/2000
1/1 [==============================] - 0s 5ms/step - loss: 0.5939 - accuracy: 0.7500
Epoch 988/2000
1/1 [==============================] - 0s 1ms/step - loss: 0.5937 - accuracy: 0.7500
Epoch 989/2000
1/1 [==============================] - 0s 4ms/step - loss: 0.5936 - accuracy: 0.7500
Epoch 990/2000
1/1 [==============================] - 0s 3ms/step - loss: 0.5934 - accuracy: 0.7500
Epoch 991/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.5933 - accuracy: 0.7500
Epoch 992/2000
1/1 [==============================] - 0s 3ms/step - loss: 0.5931 - accuracy: 0.7500
Epoch 993/2000
1/1 [==============================] - 0s 1ms/step - loss: 0.5930 - accuracy: 0.7500
Epoch 994/2000


Epoch 1065/2000
1/1 [==============================] - 0s 1ms/step - loss: 0.5813 - accuracy: 0.7500
Epoch 1066/2000
1/1 [==============================] - 0s 9ms/step - loss: 0.5811 - accuracy: 0.7500
Epoch 1067/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.5809 - accuracy: 0.7500
Epoch 1068/2000
1/1 [==============================] - 0s 1ms/step - loss: 0.5808 - accuracy: 0.7500
Epoch 1069/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.5806 - accuracy: 0.7500
Epoch 1070/2000
1/1 [==============================] - 0s 3ms/step - loss: 0.5804 - accuracy: 0.7500
Epoch 1071/2000
1/1 [==============================] - 0s 1ms/step - loss: 0.5803 - accuracy: 0.7500
Epoch 1072/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.5801 - accuracy: 0.7500
Epoch 1073/2000
1/1 [==============================] - 0s 7ms/step - loss: 0.5799 - accuracy: 0.7500
Epoch 1074/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.5798 - accurac

1/1 [==============================] - 0s 3ms/step - loss: 0.5674 - accuracy: 0.7500
Epoch 1147/2000
1/1 [==============================] - 0s 1ms/step - loss: 0.5672 - accuracy: 0.7500
Epoch 1148/2000
1/1 [==============================] - 0s 7ms/step - loss: 0.5670 - accuracy: 0.7500
Epoch 1149/2000
1/1 [==============================] - 0s 1ms/step - loss: 0.5668 - accuracy: 0.7500
Epoch 1150/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.5667 - accuracy: 0.7500
Epoch 1151/2000
1/1 [==============================] - 0s 3ms/step - loss: 0.5665 - accuracy: 0.7500
Epoch 1152/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.5663 - accuracy: 0.7500
Epoch 1153/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.5661 - accuracy: 0.7500
Epoch 1154/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.5660 - accuracy: 0.7500
Epoch 1155/2000
1/1 [==============================] - 0s 1ms/step - loss: 0.5658 - accuracy: 0.7500
Epoch 

1/1 [==============================] - 0s 3ms/step - loss: 0.5375 - accuracy: 0.7500
Epoch 1308/2000
1/1 [==============================] - 0s 3ms/step - loss: 0.5373 - accuracy: 0.7500
Epoch 1309/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.5371 - accuracy: 0.7500
Epoch 1310/2000
1/1 [==============================] - 0s 5ms/step - loss: 0.5369 - accuracy: 0.7500
Epoch 1311/2000
1/1 [==============================] - 0s 3ms/step - loss: 0.5368 - accuracy: 0.7500
Epoch 1312/2000
1/1 [==============================] - 0s 9ms/step - loss: 0.5366 - accuracy: 0.7500
Epoch 1313/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.5364 - accuracy: 0.7500
Epoch 1314/2000
1/1 [==============================] - 0s 4ms/step - loss: 0.5362 - accuracy: 0.7500
Epoch 1315/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.5360 - accuracy: 0.7500
Epoch 1316/2000
1/1 [==============================] - 0s 4ms/step - loss: 0.5358 - accuracy: 0.7500
Epoch 

1/1 [==============================] - 0s 2ms/step - loss: 0.5046 - accuracy: 0.7500
Epoch 1470/2000
1/1 [==============================] - 0s 1ms/step - loss: 0.5044 - accuracy: 0.7500
Epoch 1471/2000
1/1 [==============================] - 0s 1ms/step - loss: 0.5042 - accuracy: 0.7500
Epoch 1472/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.5040 - accuracy: 0.7500
Epoch 1473/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.5038 - accuracy: 0.7500
Epoch 1474/2000
1/1 [==============================] - 0s 1ms/step - loss: 0.5036 - accuracy: 0.7500
Epoch 1475/2000
1/1 [==============================] - ETA: 0s - loss: 0.5034 - accuracy: 0.75 - 0s 5ms/step - loss: 0.5034 - accuracy: 0.7500
Epoch 1476/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.5031 - accuracy: 0.7500
Epoch 1477/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.5029 - accuracy: 0.7500
Epoch 1478/2000
1/1 [==============================] - 0s 2ms/ste

1/1 [==============================] - 0s 2ms/step - loss: 0.4691 - accuracy: 0.7500
Epoch 1631/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.4688 - accuracy: 0.7500
Epoch 1632/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.4686 - accuracy: 0.7500
Epoch 1633/2000
1/1 [==============================] - 0s 1ms/step - loss: 0.4684 - accuracy: 0.7500
Epoch 1634/2000
1/1 [==============================] - 0s 4ms/step - loss: 0.4681 - accuracy: 0.7500
Epoch 1635/2000
1/1 [==============================] - 0s 1ms/step - loss: 0.4679 - accuracy: 0.7500
Epoch 1636/2000
1/1 [==============================] - 0s 1ms/step - loss: 0.4677 - accuracy: 0.7500
Epoch 1637/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.4675 - accuracy: 0.7500
Epoch 1638/2000
1/1 [==============================] - 0s 1ms/step - loss: 0.4672 - accuracy: 0.7500
Epoch 1639/2000
1/1 [==============================] - 0s 6ms/step - loss: 0.4670 - accuracy: 0.7500
Epoch 

1/1 [==============================] - 0s 3ms/step - loss: 0.4307 - accuracy: 1.0000
Epoch 1793/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.4304 - accuracy: 1.0000
Epoch 1794/2000
1/1 [==============================] - 0s 1ms/step - loss: 0.4302 - accuracy: 1.0000
Epoch 1795/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.4299 - accuracy: 1.0000
Epoch 1796/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.4297 - accuracy: 1.0000
Epoch 1797/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.4294 - accuracy: 1.0000
Epoch 1798/2000
1/1 [==============================] - 0s 3ms/step - loss: 0.4292 - accuracy: 1.0000
Epoch 1799/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.4290 - accuracy: 1.0000
Epoch 1800/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.4287 - accuracy: 1.0000
Epoch 1801/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.4285 - accuracy: 1.0000
Epoch 

1/1 [==============================] - 0s 6ms/step - loss: 0.3906 - accuracy: 1.0000
Epoch 1955/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.3903 - accuracy: 1.0000
Epoch 1956/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.3901 - accuracy: 1.0000
Epoch 1957/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.3899 - accuracy: 1.0000
Epoch 1958/2000
1/1 [==============================] - 0s 3ms/step - loss: 0.3896 - accuracy: 1.0000
Epoch 1959/2000
1/1 [==============================] - 0s 5ms/step - loss: 0.3894 - accuracy: 1.0000
Epoch 1960/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.3891 - accuracy: 1.0000
Epoch 1961/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.3889 - accuracy: 1.0000
Epoch 1962/2000
1/1 [==============================] - 0s 1ms/step - loss: 0.3886 - accuracy: 1.0000
Epoch 1963/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.3884 - accuracy: 1.0000
Epoch 

In [6]:
model_bp.get_weights()

[array([[ 4.2083344, -2.2052717],
        [ 4.2083344, -2.2052717]], dtype=float32),
 array([-1.355447 ,  3.1652527], dtype=float32),
 array([[3.6984003],
        [2.7460241]], dtype=float32),
 array([-4.5641084], dtype=float32)]

In [166]:
# MLP model
class StochasticMLP(Model):
    
    def __init__(self, hidden_layer_sizes=[100], n_outputs=10):
        super(StochasticMLP, self).__init__()
        self.hidden_layer_sizes = hidden_layer_sizes
        self.fc_layers = [Dense(layer_size) for layer_size in hidden_layer_sizes]
        self.output_layer = Dense(n_outputs)
    
    def call(self, x):
        
        #x = Flatten()(x)
        
        network = []
        
        for i, layer in enumerate(self.fc_layers):
            
            logits = layer(x)
            x = tfp.distributions.Bernoulli(logits=logits).sample()
            network.append(x)

        final_logits = self.output_layer(x) # initial the weight of output layer
            
        return network
    
    def propose_new_state(self, x, h, y):
        '''returns new proposed h values
        x: inputs
        h: list of layer values
        y: labels
        returns h_proposed'''
        
        x = Flatten()(x)

        #h_current = [h['h%i_values' % i] for i in range(len(self.fc_layers))]
        h_current = h
        h_current = [tf.cast(h_i, dtype=tf.float32) for h_i in h_current]
        
        in_layers = self.fc_layers
        out_layers = self.fc_layers[1:] + [self.output_layer]
        
        prev_vals = [x] + h_current[:-1]
        curr_vals = h_current
        next_vals = h_current[1:] + [y]
        
        h_new = []
        
        for i, (in_layer, out_layer, pv, cv, nv) in enumerate(
            zip(in_layers, out_layers, prev_vals, curr_vals, next_vals)):
            
            prob_parents = tf.math.sigmoid(in_layer(pv))
            
            out_layer_weights = out_layer.get_weights()[0]
            
            next_logits = out_layer(cv)
            
            # if h1 node is a 1, subtract its weight
            next_logits_if_node_is_0 = next_logits[:, tf.newaxis, :] - cv[:, :, np.newaxis] * out_layer_weights[tf.newaxis, :, :]
        
            # if h1 node is a 0, add its weight
            next_logits_if_node_is_1 = next_logits[:, tf.newaxis, :] + (1 - cv[:, :, np.newaxis]) * out_layer_weights[tf.newaxis, :, :]
            
            # calculate total sum of log probability
            nv_tiled = tf.cast(np.tile(nv[:, np.newaxis, :], (1, cv.shape[-1], 1)), dtype=tf.float32)
                
            logprob_children_if_node_is_0 = tf.reduce_sum(tf.nn.sigmoid_cross_entropy_with_logits(
                labels=nv_tiled, logits=next_logits_if_node_is_0), axis=-1)

            logprob_children_if_node_is_1  = tf.reduce_sum(tf.nn.sigmoid_cross_entropy_with_logits(
                labels=nv_tiled, logits=next_logits_if_node_is_1), axis=-1)
                
            
            prob_0 = (1 - prob_parents) * tf.math.exp(logprob_children_if_node_is_0)
            prob_1 = prob_parents * tf.math.exp(logprob_children_if_node_is_1)
        
            prob = prob_1 / (prob_1 + prob_0)
            
            new_layer_state = tfp.distributions.Bernoulli(probs=prob).sample()
            h_new.append(new_layer_state)
       
        # not sample output labels
        # h_new['labels'] = tf.argmax(
        #     tfp.distributions.Multinomial(10, logits=self.output_layer(h_current[-1])).sample(),
        #     axis=1)
            
        return h_new
    
    def target_log_prob(self, x, h, y):
        
        x = Flatten()(x)
        
        h_current = h
        h_current = [tf.cast(h_i, dtype=tf.float32) for h_i in h_current]
        
        h_previous = [x] + h_current[:-1]
        
        nlog_prob = 0. # negative log probability
        
        for i, (cv, pv, layer) in enumerate(
            zip(h_current, h_previous, self.fc_layers)):
            
            ce = tf.nn.sigmoid_cross_entropy_with_logits(
                labels=cv, logits=layer(pv))
            
            nlog_prob += tf.reduce_sum(ce, axis = -1)
            
        #nlog_prob += tf.nn.sparse_softmax_cross_entropy_with_logits(
        #    labels=tf.cast(y, tf.int32), logits=self.output_layer(h_current[-1]))
        
        fce = tf.nn.sigmoid_cross_entropy_with_logits(
            labels=tf.cast(y, tf.float32), logits=self.output_layer(h_current[-1]))
        nlog_prob += tf.reduce_sum(fce, axis = -1)
            
        return -1 * nlog_prob

    def target_log_prob2(self, x, h, y):

        h_current = tf.split(h, self.hidden_layer_sizes, axis = 1)
        #print(h_current)
        h_previous = [x] + h_current[:-1]
        #print(h_previous)
        
        nlog_prob = 0.
        
        for i, (cv, pv, layer) in enumerate(
            zip(h_current, h_previous, self.fc_layers)):
            
            ce = tf.nn.sigmoid_cross_entropy_with_logits(
                labels=cv, logits=layer(pv))
            
            nlog_prob += tf.reduce_sum(ce, axis = -1)
        
        #print(h_current[-1])
        fce = tf.nn.sigmoid_cross_entropy_with_logits(
            labels=tf.cast(y, tf.float32), logits=self.output_layer(h_current[-1]))
        nlog_prob += tf.reduce_sum(fce, axis = -1)
        
        #print(nlog_prob)
            
        return -1 * nlog_prob
    
    def accept_reject(self, x, h, h_p, y):

        log_prob_curr = self.target_log_prob(x, h, y)
        log_prob_prop = self.target_log_prob(x, h_p, y)
        
        #ratio = [np.exp(-np.maximum(0, prop - curr)) for curr, prop in zip(log_prob_curr, log_prob_prop)]
        ratio = np.exp(-np.maximum(0, log_prob_prop - log_prob_curr))
        acceptance = tfp.distributions.Bernoulli(probs = ratio).sample()
        
        h_new = []
        
        for i in range(len(self.fc_layers)):
            #h_new['h%i_values' % i] = h_p['h%i_values' % i] * acceptance[:, np.newaxis] \
            #    + h['h%i_values' % i] * (1 - acceptance)[:, np.newaxis]
            acc_layer_state = h_p[i] * acceptance[:, np.newaxis] + h[i] * (1 - acceptance)[:, np.newaxis]
            h_new.append(acc_layer_state)
        
        return h_new
    
    # new proposing-state method with HamiltonianMonteCarlo
    def propose_new_state_hamiltonian(self, x, h, y):
    
        h_current = h
        h_current = [tf.cast(h_i, dtype=tf.float32) for h_i in h_current]
        h_current = h_current[0]

        # initialize the HMC transition kernel
        adaptive_hmc = tfp.mcmc.SimpleStepSizeAdaptation(tfp.mcmc.HamiltonianMonteCarlo(
            target_log_prob_fn = lambda v: self.target_log_prob2(x, v, y),
            num_leapfrog_steps = 2,
            step_size = pow(1000, -1/4)),
            num_adaptation_steps=int(100 * 0.8))

        # run the chain (with burn-in)
        num_results = 1
        num_burnin_steps = 100

        samples = tfp.mcmc.sample_chain(
            num_results = num_results,
            num_burnin_steps = num_burnin_steps,
            current_state = h_current, # may need to be reshaped
            kernel = adaptive_hmc,
            trace_fn = None)
        
        #print(samples[0])

        new_state = tf.math.sign(tf.math.sign(samples[0]) - 1) + 1
        h_new = tf.split(new_state, self.hidden_layer_sizes, axis = 1)

        return(h_new)
    
    def update_weights(self, x, h, y, lr = 0.01):
        
        optimizer = tf.keras.optimizers.SGD(learning_rate = lr)
        with tf.GradientTape() as tape:
            loss = -1 * tf.reduce_mean(self.target_log_prob(x, h, y))
        
        grads = tape.gradient(loss, self.trainable_weights)
        optimizer.apply_gradients(zip(grads, self.trainable_weights))

    def get_predictions(self, x):

        logits = 0.0
        for layer in self.fc_layers:
            logits = layer(x)
            x = tf.math.sigmoid(logits)
        
        logits = self.output_layer(x)
        labels = tfp.distributions.Bernoulli(logits = logits).sample()

        return labels

In [167]:
train_ds = tf.data.Dataset.from_tensor_slices((x_train, y_train)).batch(4)

In [168]:
model = StochasticMLP(hidden_layer_sizes = [2], n_outputs=1)

In [169]:
network = [model.call(images) for images, labels in train_ds]

In [170]:
# initialize weights for model
model.fc_layers[0].set_weights(l_0)
model.output_layer.set_weights(l_1)

In [171]:
network = [model.call(images) for images, labels in train_ds]
#network

In [172]:
#print(model.fc_layers[0].get_weights())
#print(model.output_layer.get_weights())
#network

In [173]:
epochs = 100

for epoch in range(epochs):
    
    loss = 0.0
    acc = 0.0
    for bs, (images, labels) in enumerate(train_ds):
        
        # only one mini-batch
        model.update_weights(images, network[bs], labels, 0.01)
        
        h_proposed = [model.propose_new_state(images, net, labels) for (images, labels), net in zip(train_ds, network)]
        network_new = [model.accept_reject(images, net, net_proposed, labels) 
                                for (images, labels), net, net_proposed in zip(train_ds, network, h_proposed)]
        
        #network_new = [model.propose_new_state_hamiltonian(images, net, labels) for (images, labels), net in 
        #               zip(train_ds, network)]
        network = network_new
        
        loss += -1 * tf.reduce_mean(model.target_log_prob(images, network[bs], labels))
    
    preds = [model.get_predictions(images) for images, labels in train_ds]
    train_acc = accuracy_score(np.array(preds[0]), y_train)
    print("Epoch %d: - loss: %.4f - accuracy: %.4f" % (epoch, loss, train_acc))
    #print(preds)

Epoch 0: - loss: 2.3161 - accuracy: 0.2500
Epoch 1: - loss: 2.4667 - accuracy: 0.5000
Epoch 2: - loss: 2.5620 - accuracy: 0.2500
Epoch 3: - loss: 2.9394 - accuracy: 0.2500
Epoch 4: - loss: 2.4035 - accuracy: 0.2500
Epoch 5: - loss: 2.4990 - accuracy: 0.5000
Epoch 6: - loss: 2.4972 - accuracy: 0.2500
Epoch 7: - loss: 2.3957 - accuracy: 0.5000
Epoch 8: - loss: 2.5130 - accuracy: 0.0000
Epoch 9: - loss: 2.8320 - accuracy: 0.5000
Epoch 10: - loss: 2.5567 - accuracy: 0.7500
Epoch 11: - loss: 2.6658 - accuracy: 1.0000
Epoch 12: - loss: 2.3874 - accuracy: 0.7500
Epoch 13: - loss: 2.1111 - accuracy: 0.7500
Epoch 14: - loss: 2.6577 - accuracy: 0.7500
Epoch 15: - loss: 2.6540 - accuracy: 0.5000
Epoch 16: - loss: 2.5457 - accuracy: 0.5000
Epoch 17: - loss: 2.2705 - accuracy: 0.2500
Epoch 18: - loss: 2.2691 - accuracy: 1.0000
Epoch 19: - loss: 2.8108 - accuracy: 0.5000
Epoch 20: - loss: 2.4367 - accuracy: 0.5000
Epoch 21: - loss: 2.6431 - accuracy: 0.5000
Epoch 22: - loss: 2.1159 - accuracy: 1.000

In [147]:
print(model.fc_layers[0].get_weights())
print(model.output_layer.get_weights())

[array([[ 1.0114074, -1.0041794],
       [ 1.0114074, -1.0116714]], dtype=float32), array([-0.4886636 ,  0.99756694], dtype=float32)]
[array([[1.0085255 ],
       [0.99358153]], dtype=float32), array([-1.0046173], dtype=float32)]


In [111]:
a=[0]
a[-1]

0