In [1]:
# Use exclusive OR to test the MH_MLP code
import tensorflow as tf
import tensorflow_probability as tfp
import numpy as np
import random
from tensorflow import keras
from tensorflow.keras import layers
from tensorflow.keras import initializers
from tensorflow.keras import Model
from tensorflow.keras.layers import Flatten, Dense
from sklearn.metrics import accuracy_score

In [2]:
# Set data
x_train = np.array([[0, 0],
           [0, 1],
           [1, 0],
           [1, 1]])
y_train = np.array([[0],
           [1],
           [1],
           [0]])
print(x_train)
print(y_train)

[[0 0]
 [0 1]
 [1 0]
 [1 1]]
[[0]
 [1]
 [1]
 [0]]


In [3]:
# Standard BP
model_bp = keras.Sequential(
    [
        keras.Input(shape=(2,)),
        layers.Dense(2, activation = "sigmoid"),
        layers.Dense(1, activation = "sigmoid")
    ]
)
model_bp.summary()
model_bp.get_weights()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 2)                 6         
_________________________________________________________________
dense_1 (Dense)              (None, 1)                 3         
Total params: 9
Trainable params: 9
Non-trainable params: 0
_________________________________________________________________


[array([[-0.39494896, -0.14592326],
        [-0.7308444 ,  0.17364275]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[-0.5962892],
        [-0.6706042]], dtype=float32),
 array([0.], dtype=float32)]

In [4]:
# Set weight
w_0 = np.array([[1, -1], [1, -1]], dtype = "float32")
b_0 = np.array([-0.5, 1], dtype = "float32")
l_0 = [w_0, b_0]

w_1 = np.array([[1], [1]], dtype = "float32")
b_1 = np.array([-1], dtype = "float32")
l_1 = [w_1, b_1]

model_bp.layers[0].set_weights(l_0)
model_bp.layers[1].set_weights(l_1)
model_bp.get_weights()

[array([[ 1., -1.],
        [ 1., -1.]], dtype=float32),
 array([-0.5,  1. ], dtype=float32),
 array([[1.],
        [1.]], dtype=float32),
 array([-1.], dtype=float32)]

In [5]:
import time
batch_size = 4
epochs = 1700
opt = tf.keras.optimizers.SGD(learning_rate=0.1)

st = time.time()
model_bp.compile(loss="binary_crossentropy", optimizer=opt, metrics=["accuracy"])
model_bp.fit(x_train, y_train, batch_size=batch_size, epochs=epochs)
print(time.time() - st)

Epoch 1/1700
1/1 [==============================] - 0s 1ms/step - loss: 0.6885 - accuracy: 0.5000
Epoch 2/1700
1/1 [==============================] - 0s 1ms/step - loss: 0.6883 - accuracy: 0.5000
Epoch 3/1700
1/1 [==============================] - 0s 1ms/step - loss: 0.6882 - accuracy: 0.5000
Epoch 4/1700
1/1 [==============================] - 0s 1ms/step - loss: 0.6881 - accuracy: 0.5000
Epoch 5/1700
1/1 [==============================] - 0s 1ms/step - loss: 0.6880 - accuracy: 0.5000
Epoch 6/1700
1/1 [==============================] - 0s 2ms/step - loss: 0.6879 - accuracy: 0.5000
Epoch 7/1700
1/1 [==============================] - 0s 2ms/step - loss: 0.6878 - accuracy: 0.5000
Epoch 8/1700
1/1 [==============================] - 0s 1ms/step - loss: 0.6877 - accuracy: 0.5000
Epoch 9/1700
1/1 [==============================] - 0s 1ms/step - loss: 0.6876 - accuracy: 0.5000
Epoch 10/1700
1/1 [==============================] - 0s 1ms/step - loss: 0.6875 - accuracy: 0.5000
Epoch 11/1700
1/1 [

1/1 [==============================] - 0s 9ms/step - loss: 0.6832 - accuracy: 0.7500
Epoch 84/1700
1/1 [==============================] - 0s 3ms/step - loss: 0.6832 - accuracy: 0.7500
Epoch 85/1700
1/1 [==============================] - 0s 2ms/step - loss: 0.6831 - accuracy: 0.7500
Epoch 86/1700
1/1 [==============================] - 0s 1ms/step - loss: 0.6831 - accuracy: 0.7500
Epoch 87/1700
1/1 [==============================] - 0s 1ms/step - loss: 0.6830 - accuracy: 0.7500
Epoch 88/1700
1/1 [==============================] - 0s 5ms/step - loss: 0.6829 - accuracy: 0.7500
Epoch 89/1700
1/1 [==============================] - 0s 2ms/step - loss: 0.6829 - accuracy: 0.7500
Epoch 90/1700
1/1 [==============================] - 0s 1ms/step - loss: 0.6828 - accuracy: 0.7500
Epoch 91/1700
1/1 [==============================] - 0s 2ms/step - loss: 0.6828 - accuracy: 0.7500
Epoch 92/1700
1/1 [==============================] - 0s 2ms/step - loss: 0.6827 - accuracy: 0.7500
Epoch 93/1700
1/1 [=====

1/1 [==============================] - 0s 2ms/step - loss: 0.6787 - accuracy: 0.7500
Epoch 166/1700
1/1 [==============================] - 0s 3ms/step - loss: 0.6786 - accuracy: 0.7500
Epoch 167/1700
1/1 [==============================] - 0s 1ms/step - loss: 0.6786 - accuracy: 0.7500
Epoch 168/1700
1/1 [==============================] - 0s 2ms/step - loss: 0.6785 - accuracy: 0.7500
Epoch 169/1700
1/1 [==============================] - 0s 3ms/step - loss: 0.6784 - accuracy: 0.7500
Epoch 170/1700
1/1 [==============================] - 0s 3ms/step - loss: 0.6784 - accuracy: 0.7500
Epoch 171/1700
1/1 [==============================] - 0s 1ms/step - loss: 0.6783 - accuracy: 0.7500
Epoch 172/1700
1/1 [==============================] - 0s 2ms/step - loss: 0.6783 - accuracy: 0.7500
Epoch 173/1700
1/1 [==============================] - 0s 2ms/step - loss: 0.6782 - accuracy: 0.7500
Epoch 174/1700
1/1 [==============================] - 0s 3ms/step - loss: 0.6781 - accuracy: 0.7500
Epoch 175/1700


1/1 [==============================] - 0s 4ms/step - loss: 0.6737 - accuracy: 0.7500
Epoch 248/1700
1/1 [==============================] - 0s 2ms/step - loss: 0.6736 - accuracy: 0.7500
Epoch 249/1700
1/1 [==============================] - 0s 2ms/step - loss: 0.6735 - accuracy: 0.7500
Epoch 250/1700
1/1 [==============================] - 0s 2ms/step - loss: 0.6735 - accuracy: 0.7500
Epoch 251/1700
1/1 [==============================] - 0s 2ms/step - loss: 0.6734 - accuracy: 0.7500
Epoch 252/1700
1/1 [==============================] - 0s 2ms/step - loss: 0.6733 - accuracy: 0.7500
Epoch 253/1700
1/1 [==============================] - 0s 3ms/step - loss: 0.6733 - accuracy: 0.7500
Epoch 254/1700
1/1 [==============================] - 0s 2ms/step - loss: 0.6732 - accuracy: 0.7500
Epoch 255/1700
1/1 [==============================] - 0s 2ms/step - loss: 0.6731 - accuracy: 0.7500
Epoch 256/1700
1/1 [==============================] - 0s 3ms/step - loss: 0.6731 - accuracy: 0.7500
Epoch 257/1700


Epoch 329/1700
1/1 [==============================] - 0s 6ms/step - loss: 0.6680 - accuracy: 0.7500
Epoch 330/1700
1/1 [==============================] - 0s 1ms/step - loss: 0.6680 - accuracy: 0.7500
Epoch 331/1700
1/1 [==============================] - 0s 1ms/step - loss: 0.6679 - accuracy: 0.7500
Epoch 332/1700
1/1 [==============================] - 0s 1ms/step - loss: 0.6678 - accuracy: 0.7500
Epoch 333/1700
1/1 [==============================] - 0s 1ms/step - loss: 0.6678 - accuracy: 0.7500
Epoch 334/1700
1/1 [==============================] - 0s 2ms/step - loss: 0.6677 - accuracy: 0.7500
Epoch 335/1700
1/1 [==============================] - 0s 3ms/step - loss: 0.6676 - accuracy: 0.7500
Epoch 336/1700
1/1 [==============================] - 0s 1ms/step - loss: 0.6675 - accuracy: 0.7500
Epoch 337/1700
1/1 [==============================] - 0s 2ms/step - loss: 0.6675 - accuracy: 0.7500
Epoch 338/1700
1/1 [==============================] - 0s 2ms/step - loss: 0.6674 - accuracy: 0.7500


1/1 [==============================] - 0s 1ms/step - loss: 0.6618 - accuracy: 0.7500
Epoch 411/1700
1/1 [==============================] - 0s 1ms/step - loss: 0.6618 - accuracy: 0.7500
Epoch 412/1700
1/1 [==============================] - 0s 1ms/step - loss: 0.6617 - accuracy: 0.7500
Epoch 413/1700
1/1 [==============================] - 0s 2ms/step - loss: 0.6616 - accuracy: 0.7500
Epoch 414/1700
1/1 [==============================] - 0s 1ms/step - loss: 0.6615 - accuracy: 0.7500
Epoch 415/1700
1/1 [==============================] - 0s 2ms/step - loss: 0.6614 - accuracy: 0.7500
Epoch 416/1700
1/1 [==============================] - 0s 6ms/step - loss: 0.6613 - accuracy: 0.7500
Epoch 417/1700
1/1 [==============================] - 0s 1ms/step - loss: 0.6613 - accuracy: 0.7500
Epoch 418/1700
1/1 [==============================] - 0s 1ms/step - loss: 0.6612 - accuracy: 0.7500
Epoch 419/1700
1/1 [==============================] - 0s 1ms/step - loss: 0.6611 - accuracy: 0.7500
Epoch 420/1700


1/1 [==============================] - 0s 1ms/step - loss: 0.6548 - accuracy: 0.7500
Epoch 493/1700
1/1 [==============================] - 0s 3ms/step - loss: 0.6547 - accuracy: 0.7500
Epoch 494/1700
1/1 [==============================] - 0s 2ms/step - loss: 0.6546 - accuracy: 0.7500
Epoch 495/1700
1/1 [==============================] - 0s 2ms/step - loss: 0.6545 - accuracy: 0.7500
Epoch 496/1700
1/1 [==============================] - 0s 1ms/step - loss: 0.6544 - accuracy: 0.7500
Epoch 497/1700
1/1 [==============================] - 0s 1ms/step - loss: 0.6544 - accuracy: 0.7500
Epoch 498/1700
1/1 [==============================] - 0s 5ms/step - loss: 0.6543 - accuracy: 0.7500
Epoch 499/1700
1/1 [==============================] - 0s 2ms/step - loss: 0.6542 - accuracy: 0.7500
Epoch 500/1700
1/1 [==============================] - 0s 2ms/step - loss: 0.6541 - accuracy: 0.7500
Epoch 501/1700
1/1 [==============================] - 0s 3ms/step - loss: 0.6540 - accuracy: 0.7500
Epoch 502/1700


1/1 [==============================] - 0s 4ms/step - loss: 0.6470 - accuracy: 0.7500
Epoch 575/1700
1/1 [==============================] - 0s 1ms/step - loss: 0.6469 - accuracy: 0.7500
Epoch 576/1700
1/1 [==============================] - 0s 2ms/step - loss: 0.6468 - accuracy: 0.7500
Epoch 577/1700
1/1 [==============================] - 0s 1ms/step - loss: 0.6467 - accuracy: 0.7500
Epoch 578/1700
1/1 [==============================] - 0s 2ms/step - loss: 0.6466 - accuracy: 0.7500
Epoch 579/1700
1/1 [==============================] - 0s 2ms/step - loss: 0.6465 - accuracy: 0.7500
Epoch 580/1700
1/1 [==============================] - 0s 1ms/step - loss: 0.6464 - accuracy: 0.7500
Epoch 581/1700
1/1 [==============================] - 0s 3ms/step - loss: 0.6463 - accuracy: 0.7500
Epoch 582/1700
1/1 [==============================] - 0s 1ms/step - loss: 0.6462 - accuracy: 0.7500
Epoch 583/1700
1/1 [==============================] - 0s 1ms/step - loss: 0.6461 - accuracy: 0.7500
Epoch 584/1700


1/1 [==============================] - 0s 2ms/step - loss: 0.6385 - accuracy: 0.7500
Epoch 656/1700
1/1 [==============================] - 0s 1ms/step - loss: 0.6383 - accuracy: 0.7500
Epoch 657/1700
1/1 [==============================] - 0s 2ms/step - loss: 0.6382 - accuracy: 0.7500
Epoch 658/1700
1/1 [==============================] - 0s 1ms/step - loss: 0.6381 - accuracy: 0.7500
Epoch 659/1700
1/1 [==============================] - 0s 2ms/step - loss: 0.6380 - accuracy: 0.7500
Epoch 660/1700
1/1 [==============================] - 0s 3ms/step - loss: 0.6379 - accuracy: 0.7500
Epoch 661/1700
1/1 [==============================] - 0s 2ms/step - loss: 0.6378 - accuracy: 0.7500
Epoch 662/1700
1/1 [==============================] - 0s 2ms/step - loss: 0.6377 - accuracy: 0.7500
Epoch 663/1700
1/1 [==============================] - 0s 2ms/step - loss: 0.6376 - accuracy: 0.7500
Epoch 664/1700
1/1 [==============================] - 0s 6ms/step - loss: 0.6374 - accuracy: 0.7500
Epoch 665/1700


1/1 [==============================] - 0s 4ms/step - loss: 0.6289 - accuracy: 0.7500
Epoch 738/1700
1/1 [==============================] - 0s 4ms/step - loss: 0.6288 - accuracy: 0.7500
Epoch 739/1700
1/1 [==============================] - 0s 1ms/step - loss: 0.6286 - accuracy: 0.7500
Epoch 740/1700
1/1 [==============================] - 0s 1ms/step - loss: 0.6285 - accuracy: 0.7500
Epoch 741/1700
1/1 [==============================] - 0s 1ms/step - loss: 0.6284 - accuracy: 0.7500
Epoch 742/1700
1/1 [==============================] - 0s 3ms/step - loss: 0.6283 - accuracy: 0.7500
Epoch 743/1700
1/1 [==============================] - 0s 2ms/step - loss: 0.6282 - accuracy: 0.7500
Epoch 744/1700
1/1 [==============================] - 0s 1ms/step - loss: 0.6280 - accuracy: 0.7500
Epoch 745/1700
1/1 [==============================] - 0s 1ms/step - loss: 0.6279 - accuracy: 0.7500
Epoch 746/1700
1/1 [==============================] - 0s 2ms/step - loss: 0.6278 - accuracy: 0.7500
Epoch 747/1700


1/1 [==============================] - 0s 2ms/step - loss: 0.6184 - accuracy: 0.7500
Epoch 820/1700
1/1 [==============================] - 0s 2ms/step - loss: 0.6182 - accuracy: 0.7500
Epoch 821/1700
1/1 [==============================] - 0s 8ms/step - loss: 0.6181 - accuracy: 0.7500
Epoch 822/1700
1/1 [==============================] - 0s 3ms/step - loss: 0.6180 - accuracy: 0.7500
Epoch 823/1700
1/1 [==============================] - 0s 2ms/step - loss: 0.6178 - accuracy: 0.7500
Epoch 824/1700
1/1 [==============================] - 0s 1ms/step - loss: 0.6177 - accuracy: 0.7500
Epoch 825/1700
1/1 [==============================] - 0s 1ms/step - loss: 0.6176 - accuracy: 0.7500
Epoch 826/1700
1/1 [==============================] - 0s 1ms/step - loss: 0.6174 - accuracy: 0.7500
Epoch 827/1700
1/1 [==============================] - 0s 2ms/step - loss: 0.6173 - accuracy: 0.7500
Epoch 828/1700
1/1 [==============================] - 0s 2ms/step - loss: 0.6172 - accuracy: 0.7500
Epoch 829/1700


1/1 [==============================] - 0s 2ms/step - loss: 0.6069 - accuracy: 0.7500
Epoch 902/1700
1/1 [==============================] - 0s 1ms/step - loss: 0.6068 - accuracy: 0.7500
Epoch 903/1700
1/1 [==============================] - 0s 2ms/step - loss: 0.6066 - accuracy: 0.7500
Epoch 904/1700
1/1 [==============================] - 0s 1ms/step - loss: 0.6065 - accuracy: 0.7500
Epoch 905/1700
1/1 [==============================] - 0s 2ms/step - loss: 0.6063 - accuracy: 0.7500
Epoch 906/1700
1/1 [==============================] - 0s 2ms/step - loss: 0.6062 - accuracy: 0.7500
Epoch 907/1700
1/1 [==============================] - 0s 4ms/step - loss: 0.6060 - accuracy: 0.7500
Epoch 908/1700
1/1 [==============================] - 0s 1ms/step - loss: 0.6059 - accuracy: 0.7500
Epoch 909/1700
1/1 [==============================] - 0s 1ms/step - loss: 0.6057 - accuracy: 0.7500
Epoch 910/1700
1/1 [==============================] - 0s 4ms/step - loss: 0.6056 - accuracy: 0.7500
Epoch 911/1700


1/1 [==============================] - 0s 1ms/step - loss: 0.5945 - accuracy: 0.7500
Epoch 984/1700
1/1 [==============================] - 0s 2ms/step - loss: 0.5944 - accuracy: 0.7500
Epoch 985/1700
1/1 [==============================] - 0s 2ms/step - loss: 0.5942 - accuracy: 0.7500
Epoch 986/1700
1/1 [==============================] - 0s 2ms/step - loss: 0.5941 - accuracy: 0.7500
Epoch 987/1700
1/1 [==============================] - 0s 4ms/step - loss: 0.5939 - accuracy: 0.7500
Epoch 988/1700
1/1 [==============================] - 0s 2ms/step - loss: 0.5937 - accuracy: 0.7500
Epoch 989/1700
1/1 [==============================] - 0s 2ms/step - loss: 0.5936 - accuracy: 0.7500
Epoch 990/1700
1/1 [==============================] - 0s 2ms/step - loss: 0.5934 - accuracy: 0.7500
Epoch 991/1700
1/1 [==============================] - 0s 1ms/step - loss: 0.5933 - accuracy: 0.7500
Epoch 992/1700
1/1 [==============================] - 0s 2ms/step - loss: 0.5931 - accuracy: 0.7500
Epoch 993/1700


1/1 [==============================] - 0s 3ms/step - loss: 0.5814 - accuracy: 0.7500
Epoch 1065/1700
1/1 [==============================] - 0s 2ms/step - loss: 0.5813 - accuracy: 0.7500
Epoch 1066/1700
1/1 [==============================] - 0s 2ms/step - loss: 0.5811 - accuracy: 0.7500
Epoch 1067/1700
1/1 [==============================] - 0s 4ms/step - loss: 0.5809 - accuracy: 0.7500
Epoch 1068/1700
1/1 [==============================] - 0s 2ms/step - loss: 0.5808 - accuracy: 0.7500
Epoch 1069/1700
1/1 [==============================] - 0s 2ms/step - loss: 0.5806 - accuracy: 0.7500
Epoch 1070/1700
1/1 [==============================] - 0s 2ms/step - loss: 0.5804 - accuracy: 0.7500
Epoch 1071/1700
1/1 [==============================] - 0s 2ms/step - loss: 0.5803 - accuracy: 0.7500
Epoch 1072/1700
1/1 [==============================] - 0s 3ms/step - loss: 0.5801 - accuracy: 0.7500
Epoch 1073/1700
1/1 [==============================] - 0s 2ms/step - loss: 0.5799 - accuracy: 0.7500
Epoch 

1/1 [==============================] - 0s 1ms/step - loss: 0.5675 - accuracy: 0.7500
Epoch 1146/1700
1/1 [==============================] - 0s 4ms/step - loss: 0.5674 - accuracy: 0.7500
Epoch 1147/1700
1/1 [==============================] - 0s 3ms/step - loss: 0.5672 - accuracy: 0.7500
Epoch 1148/1700
1/1 [==============================] - 0s 1ms/step - loss: 0.5670 - accuracy: 0.7500
Epoch 1149/1700
1/1 [==============================] - 0s 2ms/step - loss: 0.5668 - accuracy: 0.7500
Epoch 1150/1700
1/1 [==============================] - 0s 3ms/step - loss: 0.5667 - accuracy: 0.7500
Epoch 1151/1700
1/1 [==============================] - 0s 2ms/step - loss: 0.5665 - accuracy: 0.7500
Epoch 1152/1700
1/1 [==============================] - 0s 2ms/step - loss: 0.5663 - accuracy: 0.7500
Epoch 1153/1700
1/1 [==============================] - 0s 4ms/step - loss: 0.5661 - accuracy: 0.7500
Epoch 1154/1700
1/1 [==============================] - 0s 2ms/step - loss: 0.5660 - accuracy: 0.7500
Epoch 

1/1 [==============================] - 0s 4ms/step - loss: 0.5529 - accuracy: 0.7500
Epoch 1227/1700
1/1 [==============================] - 0s 3ms/step - loss: 0.5527 - accuracy: 0.7500
Epoch 1228/1700
1/1 [==============================] - 0s 4ms/step - loss: 0.5525 - accuracy: 0.7500
Epoch 1229/1700
1/1 [==============================] - 0s 2ms/step - loss: 0.5523 - accuracy: 0.7500
Epoch 1230/1700
1/1 [==============================] - 0s 2ms/step - loss: 0.5522 - accuracy: 0.7500
Epoch 1231/1700
1/1 [==============================] - 0s 2ms/step - loss: 0.5520 - accuracy: 0.7500
Epoch 1232/1700
1/1 [==============================] - 0s 3ms/step - loss: 0.5518 - accuracy: 0.7500
Epoch 1233/1700
1/1 [==============================] - 0s 3ms/step - loss: 0.5516 - accuracy: 0.7500
Epoch 1234/1700
1/1 [==============================] - 0s 3ms/step - loss: 0.5514 - accuracy: 0.7500
Epoch 1235/1700
1/1 [==============================] - 0s 2ms/step - loss: 0.5512 - accuracy: 0.7500
Epoch 

1/1 [==============================] - 0s 5ms/step - loss: 0.5375 - accuracy: 0.7500
Epoch 1308/1700
1/1 [==============================] - 0s 1ms/step - loss: 0.5373 - accuracy: 0.7500
Epoch 1309/1700
1/1 [==============================] - 0s 1ms/step - loss: 0.5371 - accuracy: 0.7500
Epoch 1310/1700
1/1 [==============================] - 0s 2ms/step - loss: 0.5369 - accuracy: 0.7500
Epoch 1311/1700
1/1 [==============================] - 0s 1ms/step - loss: 0.5368 - accuracy: 0.7500
Epoch 1312/1700
1/1 [==============================] - 0s 1ms/step - loss: 0.5366 - accuracy: 0.7500
Epoch 1313/1700
1/1 [==============================] - 0s 2ms/step - loss: 0.5364 - accuracy: 0.7500
Epoch 1314/1700
1/1 [==============================] - 0s 3ms/step - loss: 0.5362 - accuracy: 0.7500
Epoch 1315/1700
1/1 [==============================] - 0s 2ms/step - loss: 0.5360 - accuracy: 0.7500
Epoch 1316/1700
1/1 [==============================] - 0s 1ms/step - loss: 0.5358 - accuracy: 0.7500
Epoch 

1/1 [==============================] - 0s 5ms/step - loss: 0.5214 - accuracy: 0.7500
Epoch 1389/1700
1/1 [==============================] - 0s 2ms/step - loss: 0.5212 - accuracy: 0.7500
Epoch 1390/1700
1/1 [==============================] - 0s 2ms/step - loss: 0.5210 - accuracy: 0.7500
Epoch 1391/1700
1/1 [==============================] - 0s 2ms/step - loss: 0.5208 - accuracy: 0.7500
Epoch 1392/1700
1/1 [==============================] - 0s 2ms/step - loss: 0.5206 - accuracy: 0.7500
Epoch 1393/1700
1/1 [==============================] - 0s 1ms/step - loss: 0.5204 - accuracy: 0.7500
Epoch 1394/1700
1/1 [==============================] - 0s 4ms/step - loss: 0.5202 - accuracy: 0.7500
Epoch 1395/1700
1/1 [==============================] - 0s 2ms/step - loss: 0.5200 - accuracy: 0.7500
Epoch 1396/1700
1/1 [==============================] - 0s 1ms/step - loss: 0.5198 - accuracy: 0.7500
Epoch 1397/1700
1/1 [==============================] - 0s 5ms/step - loss: 0.5196 - accuracy: 0.7500
Epoch 

1/1 [==============================] - 0s 2ms/step - loss: 0.5046 - accuracy: 0.7500
Epoch 1470/1700
1/1 [==============================] - 0s 3ms/step - loss: 0.5044 - accuracy: 0.7500
Epoch 1471/1700
1/1 [==============================] - 0s 2ms/step - loss: 0.5042 - accuracy: 0.7500
Epoch 1472/1700
1/1 [==============================] - 0s 2ms/step - loss: 0.5040 - accuracy: 0.7500
Epoch 1473/1700
1/1 [==============================] - 0s 4ms/step - loss: 0.5038 - accuracy: 0.7500
Epoch 1474/1700
1/1 [==============================] - 0s 2ms/step - loss: 0.5036 - accuracy: 0.7500
Epoch 1475/1700
1/1 [==============================] - 0s 2ms/step - loss: 0.5034 - accuracy: 0.7500
Epoch 1476/1700
1/1 [==============================] - 0s 2ms/step - loss: 0.5031 - accuracy: 0.7500
Epoch 1477/1700
1/1 [==============================] - 0s 1ms/step - loss: 0.5029 - accuracy: 0.7500
Epoch 1478/1700
1/1 [==============================] - 0s 1ms/step - loss: 0.5027 - accuracy: 0.7500
Epoch 

1/1 [==============================] - 0s 3ms/step - loss: 0.4871 - accuracy: 0.7500
Epoch 1551/1700
1/1 [==============================] - 0s 2ms/step - loss: 0.4869 - accuracy: 0.7500
Epoch 1552/1700
1/1 [==============================] - 0s 2ms/step - loss: 0.4866 - accuracy: 0.7500
Epoch 1553/1700
1/1 [==============================] - 0s 1ms/step - loss: 0.4864 - accuracy: 0.7500
Epoch 1554/1700
1/1 [==============================] - 0s 3ms/step - loss: 0.4862 - accuracy: 0.7500
Epoch 1555/1700
1/1 [==============================] - 0s 3ms/step - loss: 0.4860 - accuracy: 0.7500
Epoch 1556/1700
1/1 [==============================] - 0s 3ms/step - loss: 0.4858 - accuracy: 0.7500
Epoch 1557/1700
1/1 [==============================] - 0s 3ms/step - loss: 0.4855 - accuracy: 0.7500
Epoch 1558/1700
1/1 [==============================] - 0s 4ms/step - loss: 0.4853 - accuracy: 0.7500
Epoch 1559/1700
1/1 [==============================] - 0s 2ms/step - loss: 0.4851 - accuracy: 0.7500
Epoch 

1/1 [==============================] - 0s 2ms/step - loss: 0.4688 - accuracy: 0.7500
Epoch 1632/1700
1/1 [==============================] - 0s 2ms/step - loss: 0.4686 - accuracy: 0.7500
Epoch 1633/1700
1/1 [==============================] - 0s 1ms/step - loss: 0.4684 - accuracy: 0.7500
Epoch 1634/1700
1/1 [==============================] - 0s 1ms/step - loss: 0.4681 - accuracy: 0.7500
Epoch 1635/1700
1/1 [==============================] - 0s 2ms/step - loss: 0.4679 - accuracy: 0.7500
Epoch 1636/1700
1/1 [==============================] - 0s 1ms/step - loss: 0.4677 - accuracy: 0.7500
Epoch 1637/1700
1/1 [==============================] - 0s 2ms/step - loss: 0.4675 - accuracy: 0.7500
Epoch 1638/1700
1/1 [==============================] - 0s 3ms/step - loss: 0.4672 - accuracy: 0.7500
Epoch 1639/1700
1/1 [==============================] - 0s 2ms/step - loss: 0.4670 - accuracy: 0.7500
Epoch 1640/1700
1/1 [==============================] - 0s 2ms/step - loss: 0.4668 - accuracy: 0.7500
Epoch 

In [6]:
model_bp.get_weights()

[array([[ 3.7765753, -1.836392 ],
        [ 3.7765753, -1.836392 ]], dtype=float32),
 array([-1.0800517,  2.5930953], dtype=float32),
 array([[3.2728775],
        [2.1089282]], dtype=float32),
 array([-3.8079824], dtype=float32)]

In [7]:
# MLP model
class StochasticMLP(Model):
    
    def __init__(self, hidden_layer_sizes=[100], n_outputs=10):
        super(StochasticMLP, self).__init__()
        self.hidden_layer_sizes = hidden_layer_sizes
        self.fc_layers = [Dense(layer_size) for layer_size in hidden_layer_sizes]
        self.output_layer = Dense(n_outputs)
    
    def call(self, x):
        
        #x = Flatten()(x)
        
        network = []
        
        for i, layer in enumerate(self.fc_layers):
            
            logits = layer(x)
            x = tfp.distributions.Bernoulli(logits=logits).sample()
            network.append(x)

        final_logits = self.output_layer(x) # initial the weight of output layer
            
        return network
    
    def propose_new_state(self, x, h, y):
        '''returns new proposed h values
        x: inputs
        h: list of layer values
        y: labels
        returns h_proposed'''
        
        x = Flatten()(x)

        #h_current = [h['h%i_values' % i] for i in range(len(self.fc_layers))]
        h_current = h
        h_current = [tf.cast(h_i, dtype=tf.float32) for h_i in h_current]
        
        in_layers = self.fc_layers
        out_layers = self.fc_layers[1:] + [self.output_layer]
        
        prev_vals = [x] + h_current[:-1]
        curr_vals = h_current
        next_vals = h_current[1:] + [y]
        
        h_new = []
        
        for i, (in_layer, out_layer, pv, cv, nv) in enumerate(
            zip(in_layers, out_layers, prev_vals, curr_vals, next_vals)):
            
            prob_parents = tf.math.sigmoid(in_layer(pv))
            
            out_layer_weights = out_layer.get_weights()[0]
            
            next_logits = out_layer(cv)
            
            # if h1 node is a 1, subtract its weight
            next_logits_if_node_is_0 = next_logits[:, tf.newaxis, :] - cv[:, :, np.newaxis] * out_layer_weights[tf.newaxis, :, :]
        
            # if h1 node is a 0, add its weight
            next_logits_if_node_is_1 = next_logits[:, tf.newaxis, :] + (1 - cv[:, :, np.newaxis]) * out_layer_weights[tf.newaxis, :, :]
            
            # calculate total sum of log probability
            nv_tiled = tf.cast(np.tile(nv[:, np.newaxis, :], (1, cv.shape[-1], 1)), dtype=tf.float32)
                
            logprob_children_if_node_is_0 = tf.reduce_sum(tf.nn.sigmoid_cross_entropy_with_logits(
                labels=nv_tiled, logits=next_logits_if_node_is_0), axis=-1)

            logprob_children_if_node_is_1  = tf.reduce_sum(tf.nn.sigmoid_cross_entropy_with_logits(
                labels=nv_tiled, logits=next_logits_if_node_is_1), axis=-1)
                
            
            prob_0 = (1 - prob_parents) * tf.math.exp(logprob_children_if_node_is_0)
            prob_1 = prob_parents * tf.math.exp(logprob_children_if_node_is_1)
        
            prob = prob_1 / (prob_1 + prob_0)
            
            new_layer_state = tfp.distributions.Bernoulli(probs=prob).sample()
            h_new.append(new_layer_state)
       
        # not sample output labels
        # h_new['labels'] = tf.argmax(
        #     tfp.distributions.Multinomial(10, logits=self.output_layer(h_current[-1])).sample(),
        #     axis=1)
            
        return h_new
    
    def target_log_prob(self, x, h, y):
        
        x = Flatten()(x)
        
        h_current = h
        h_current = [tf.cast(h_i, dtype=tf.float32) for h_i in h_current]
        
        h_previous = [x] + h_current[:-1]
        
        nlog_prob = 0. # negative log probability
        
        for i, (cv, pv, layer) in enumerate(
            zip(h_current, h_previous, self.fc_layers)):
            
            ce = tf.nn.sigmoid_cross_entropy_with_logits(
                labels=cv, logits=layer(pv))
            
            nlog_prob += tf.reduce_sum(ce, axis = -1)
            
        #nlog_prob += tf.nn.sparse_softmax_cross_entropy_with_logits(
        #    labels=tf.cast(y, tf.int32), logits=self.output_layer(h_current[-1]))
        
        fce = tf.nn.sigmoid_cross_entropy_with_logits(
            labels=tf.cast(y, tf.float32), logits=self.output_layer(h_current[-1]))
        nlog_prob += tf.reduce_sum(fce, axis = -1)
            
        return -1 * nlog_prob

    def target_log_prob2(self, x, h, y):

        h_current = tf.split(h, self.hidden_layer_sizes, axis = 1)
        #print(h_current)
        h_previous = [x] + h_current[:-1]
        #print(h_previous)
        
        nlog_prob = 0.
        
        for i, (cv, pv, layer) in enumerate(
            zip(h_current, h_previous, self.fc_layers)):
            
            ce = tf.nn.sigmoid_cross_entropy_with_logits(
                labels=cv, logits=layer(pv))
            
            nlog_prob += tf.reduce_sum(ce, axis = -1)
        
        #print(h_current[-1])
        fce = tf.nn.sigmoid_cross_entropy_with_logits(
            labels=tf.cast(y, tf.float32), logits=self.output_layer(h_current[-1]))
        nlog_prob += tf.reduce_sum(fce, axis = -1)
        
        #print(nlog_prob)
            
        return -1 * nlog_prob
    
    def accept_reject(self, x, h, h_p, y):

        log_prob_curr = self.target_log_prob(x, h, y)
        log_prob_prop = self.target_log_prob(x, h_p, y)
        
        #ratio = [np.exp(-np.maximum(0, prop - curr)) for curr, prop in zip(log_prob_curr, log_prob_prop)]
        ratio = np.exp(-np.maximum(0, log_prob_prop - log_prob_curr))
        acceptance = tfp.distributions.Bernoulli(probs = ratio).sample()
        
        h_new = []
        
        for i in range(len(self.fc_layers)):
            #h_new['h%i_values' % i] = h_p['h%i_values' % i] * acceptance[:, np.newaxis] \
            #    + h['h%i_values' % i] * (1 - acceptance)[:, np.newaxis]
            acc_layer_state = h_p[i] * acceptance[:, np.newaxis] + h[i] * (1 - acceptance)[:, np.newaxis]
            h_new.append(acc_layer_state)
        
        return h_new
    
    # new proposing-state method with HamiltonianMonteCarlo
    def propose_new_state_hamiltonian(self, x, h, y):
    
        h_current = h
        h_current = [tf.cast(h_i, dtype=tf.float32) for h_i in h_current]
        h_current = h_current[0]

        # initialize the HMC transition kernel
        adaptive_hmc = tfp.mcmc.SimpleStepSizeAdaptation(tfp.mcmc.HamiltonianMonteCarlo(
            target_log_prob_fn = lambda v: self.target_log_prob2(x, v, y),
            num_leapfrog_steps = 2,
            step_size = pow(1000, -1/4)),
            num_adaptation_steps=int(100 * 0.8))

        # run the chain (with burn-in)
        num_results = 1
        num_burnin_steps = 100

        samples = tfp.mcmc.sample_chain(
            num_results = num_results,
            num_burnin_steps = num_burnin_steps,
            current_state = h_current, # may need to be reshaped
            kernel = adaptive_hmc,
            trace_fn = None)
        
        #print(samples[0])

        new_state = tf.math.sign(tf.math.sign(samples[0]) - 1) + 1
        #new_state = tf.cast(tf.math.greater(samples[0], 0.5), tf.int32)
        h_new = tf.split(new_state, self.hidden_layer_sizes, axis = 1)

        return(h_new)
    
    def update_weights(self, x, h, y, lr = 0.1):
        
        optimizer = tf.keras.optimizers.SGD(learning_rate = lr)
        with tf.GradientTape() as tape:
            loss = -1 * tf.reduce_mean(self.target_log_prob(x, h, y))
        
        grads = tape.gradient(loss, self.trainable_weights)
        optimizer.apply_gradients(zip(grads, self.trainable_weights))

    def get_predictions(self, x):

        logits = 0.0
        for layer in self.fc_layers:
            logits = layer(x)
            x = tf.math.sigmoid(logits)
        
        logits = self.output_layer(x)
        probs = tf.math.sigmoid(logits)
        #labels = tfp.distributions.Bernoulli(logits = logits).sample()
        labels = tf.cast(tf.math.greater(probs, 0.5), tf.int32)

        return labels

In [8]:
train_ds = tf.data.Dataset.from_tensor_slices((x_train, y_train)).batch(4)

In [9]:
model = StochasticMLP(hidden_layer_sizes = [2], n_outputs=1)

In [10]:
network = [model.call(images) for images, labels in train_ds]

In [11]:
# initialize weights for model
model.fc_layers[0].set_weights(l_0)
model.output_layer.set_weights(l_1)

In [12]:
network = [model.call(images) for images, labels in train_ds]
network

[[<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
  array([[0, 0],
         [1, 1],
         [0, 0],
         [1, 0]], dtype=int32)>]]

In [13]:
import time
epochs = 300

random.seed(1234)
start_time = time.time()
for epoch in range(epochs):
    
    loss = 0.0
    acc = 0.0
    for bs, (images, labels) in enumerate(train_ds):
        
        # only one mini-batch
        model.update_weights(images, network[bs], labels, 0.1)
        
        #h_proposed = [model.propose_new_state(images, net, labels) for (images, labels), net in zip(train_ds, network)]
        #network_new = [model.accept_reject(images, net, net_proposed, labels) 
        #                        for (images, labels), net, net_proposed in zip(train_ds, network, h_proposed)]
        
        network_new = [model.propose_new_state_hamiltonian(images, net, labels) for (images, labels), net in 
                       zip(train_ds, network)]
        network = network_new
        
        loss += -1 * tf.reduce_mean(model.target_log_prob(images, network[bs], labels))
    
    preds = [model.get_predictions(images) for images, labels in train_ds]
    train_acc = accuracy_score(np.array(preds[0]), y_train)
    print("Epoch %d/%d: - %.4fs/step - loss: %.4f - accuracy: %.4f" 
          % (epoch + 1, epochs, (time.time() - start_time) / (epoch + 1), loss, train_acc))
    #print(preds)

Epoch 1/300: - 1.4608s/step - loss: 1.5056 - accuracy: 0.5000
Epoch 2/300: - 1.3683s/step - loss: 1.4153 - accuracy: 0.5000
Epoch 3/300: - 1.3420s/step - loss: 1.5016 - accuracy: 0.5000
Epoch 4/300: - 1.3717s/step - loss: 1.4851 - accuracy: 0.5000
Epoch 5/300: - 1.3590s/step - loss: 1.4751 - accuracy: 0.5000
Epoch 6/300: - 1.3657s/step - loss: 1.3865 - accuracy: 0.5000
Epoch 7/300: - 1.3711s/step - loss: 1.3736 - accuracy: 0.5000
Epoch 8/300: - 1.3805s/step - loss: 1.3614 - accuracy: 0.5000
Epoch 9/300: - 1.4028s/step - loss: 1.3499 - accuracy: 0.5000
Epoch 10/300: - 1.4355s/step - loss: 1.4510 - accuracy: 0.5000
Epoch 11/300: - 1.4399s/step - loss: 1.5721 - accuracy: 0.5000
Epoch 12/300: - 1.4400s/step - loss: 1.5504 - accuracy: 0.5000
Epoch 13/300: - 1.4359s/step - loss: 1.4264 - accuracy: 0.5000
Epoch 14/300: - 1.4351s/step - loss: 1.4185 - accuracy: 0.5000
Epoch 15/300: - 1.4379s/step - loss: 1.3413 - accuracy: 0.5000
Epoch 16/300: - 1.4386s/step - loss: 1.3302 - accuracy: 0.5000
E

Epoch 131/300: - 1.6701s/step - loss: 0.9701 - accuracy: 0.5000
Epoch 132/300: - 1.6673s/step - loss: 0.9684 - accuracy: 0.5000
Epoch 133/300: - 1.6647s/step - loss: 0.9666 - accuracy: 0.5000
Epoch 134/300: - 1.6620s/step - loss: 0.9649 - accuracy: 0.5000
Epoch 135/300: - 1.6619s/step - loss: 0.9632 - accuracy: 0.5000
Epoch 136/300: - 1.6598s/step - loss: 0.9615 - accuracy: 0.7500
Epoch 137/300: - 1.6575s/step - loss: 0.9598 - accuracy: 0.7500
Epoch 138/300: - 1.6565s/step - loss: 0.9581 - accuracy: 0.7500
Epoch 139/300: - 1.6546s/step - loss: 0.9564 - accuracy: 0.7500
Epoch 140/300: - 1.6533s/step - loss: 0.9547 - accuracy: 0.7500
Epoch 141/300: - 1.6519s/step - loss: 0.9530 - accuracy: 0.7500
Epoch 142/300: - 1.6499s/step - loss: 0.9513 - accuracy: 0.7500
Epoch 143/300: - 1.6482s/step - loss: 0.9497 - accuracy: 0.7500
Epoch 144/300: - 1.6469s/step - loss: 0.9480 - accuracy: 0.7500
Epoch 145/300: - 1.6447s/step - loss: 0.9463 - accuracy: 0.7500
Epoch 146/300: - 1.6427s/step - loss: 0.

Epoch 260/300: - 1.5336s/step - loss: 0.7875 - accuracy: 1.0000
Epoch 261/300: - 1.5326s/step - loss: 0.7863 - accuracy: 1.0000
Epoch 262/300: - 1.5316s/step - loss: 0.7852 - accuracy: 1.0000
Epoch 263/300: - 1.5306s/step - loss: 0.7840 - accuracy: 1.0000
Epoch 264/300: - 1.5297s/step - loss: 0.7829 - accuracy: 1.0000
Epoch 265/300: - 1.5287s/step - loss: 0.7817 - accuracy: 1.0000
Epoch 266/300: - 1.5277s/step - loss: 0.7806 - accuracy: 1.0000
Epoch 267/300: - 1.5268s/step - loss: 0.7794 - accuracy: 1.0000
Epoch 268/300: - 1.5258s/step - loss: 0.7783 - accuracy: 1.0000
Epoch 269/300: - 1.5248s/step - loss: 0.7772 - accuracy: 1.0000
Epoch 270/300: - 1.5238s/step - loss: 0.7761 - accuracy: 1.0000
Epoch 271/300: - 1.5229s/step - loss: 0.7749 - accuracy: 1.0000
Epoch 272/300: - 1.5220s/step - loss: 0.7738 - accuracy: 1.0000
Epoch 273/300: - 1.5210s/step - loss: 0.7727 - accuracy: 1.0000
Epoch 274/300: - 1.5201s/step - loss: 0.7716 - accuracy: 1.0000
Epoch 275/300: - 1.5192s/step - loss: 0.

In [14]:
print(model.fc_layers[0].get_weights())
print(model.output_layer.get_weights())

[array([[ 2.5910199, -1.8571744],
       [ 2.599663 , -1.7834198]], dtype=float32), array([-0.6508659,  3.0144928], dtype=float32)]
[array([[2.0342479],
       [1.9885967]], dtype=float32), array([-2.7706556], dtype=float32)]
