In [1]:
import tensorflow as tf
import numpy as np

In [2]:
import tensorflow_probability as tfp

In [3]:
# Load MNIST
(x_dev, y_dev), (x_test, y_test) = tf.keras.datasets.mnist.load_data()

print('There are', len(x_dev), 'training images.')
print('There are', len(x_test), 'test images.')

There are 60000 training images.
There are 10000 test images.


In [4]:
train_ds = tf.data.Dataset.from_tensor_slices((x_dev, y_dev)).shuffle(10000).batch(32)
test_ds = tf.data.Dataset.from_tensor_slices((x_test, y_test)).batch(32)

In [12]:
from tensorflow.keras.layers import Flatten, Dense
from tensorflow.keras import Model


class StochasticMLP(Model):
    
    def __init__(self, hidden_layer_sizes=[100], n_outputs=10):
        super(StochasticMLP, self).__init__()
        self.hidden_layer_sizes = hidden_layer_sizes
        self.fc_layers = [Dense(layer_size) for layer_size in hidden_layer_sizes]
        self.output_layer = Dense(n_outputs)

    
    def call(self, x):
        
        x = Flatten()(x)
        
        network = []
        
        for i, layer in enumerate(self.fc_layers):
            
            logits = layer(x)
            x = tfp.distributions.Bernoulli(logits=logits).sample()
            network.append(x)     
            
        final_logits = self.output_layer(x)
        
        return network
    
    def target_log_prob(self, x, h, y):
        
        x = Flatten()(x)
        
        h_current = h
        h_current = [tf.cast(h_i, dtype=tf.float32) for h_i in h_current]
        print(h_current)
        #print(np.asarray(h_current).shape)
        h_previous = [x] + h_current[:-1]
        
        nlog_prob = 0.
        
        for i, (cv, pv, layer) in enumerate(
            zip(h_current, h_previous, self.fc_layers)):
            
            ce = tf.nn.sigmoid_cross_entropy_with_logits( # only works for discretize version
                labels=cv, logits=layer(pv))
            nlog_prob += tf.reduce_sum(ce, axis = -1)
            
        nlog_prob += tf.nn.sparse_softmax_cross_entropy_with_logits(
            labels=tf.cast(y, tf.int32), logits=self.output_layer(h_current[-1]))
            
        return -1 * nlog_prob
    
    def target_log_prob2(self, x, h, y):
        
        x = Flatten()(x)
        #print(h)
        h_current = tf.split(h, self.hidden_layer_sizes, axis = 1)
        #print(h_current)
        h_previous = [x] + h_current[:-1]
        
        nlog_prob = 0.
        
        for i, (cv, pv, layer) in enumerate(
            zip(h_current, h_previous, self.fc_layers)):
            
            ce = tf.nn.sigmoid_cross_entropy_with_logits( # only works for discretize version
                labels=cv, logits=layer(pv))
            nlog_prob += tf.reduce_sum(ce, axis = -1)
            
        nlog_prob += tf.nn.sparse_softmax_cross_entropy_with_logits(
            labels=tf.cast(y, tf.int32), logits=self.output_layer(h_current[-1]))

        print(nlog_prob)
        return -1 * nlog_prob
    
    def run_chain(self, x, h, y):
        
        #print(h)
        
        h_current = h
        h_current = [tf.cast(h_i, dtype=tf.float32) for h_i in h_current]
        h_current = tf.concat([h_current[0], h_current[1]], axis=1)
        #print(h_current)
        
        #def tlp(args):
        #    return self.target_log_prob2(x, args, y)
        
        adaptive_hmc = tfp.mcmc.SimpleStepSizeAdaptation(tfp.mcmc.HamiltonianMonteCarlo(
            target_log_prob_fn = lambda v: self.target_log_prob2(x, v, y),
            num_leapfrog_steps = 2,
            step_size = pow(1000, -1/4)),
            num_adaptation_steps=int(100 * 0.8))
        
        #print(tf.size(tlp(h_current)))
        
        # Run the chain (with burn-in).
        samples = tfp.mcmc.sample_chain(
          num_results=1, # need one step
          num_burnin_steps=100, # set to 1000
          current_state=h_current,
          kernel=adaptive_hmc,
          trace_fn=None)
        
        #print(samples[0])
        new_state = tf.math.sign(tf.math.sign(samples[0]) - 1) + 1
        h_new = tf.split(new_state, self.hidden_layer_sizes, axis = 1)
        #print(h_new)
        
        return h_new

In [13]:
model = StochasticMLP(hidden_layer_sizes = [100, 50], n_outputs=10)

In [7]:
network = [model.call(images) for images, labels in train_ds]

In [14]:
hmc = [model.run_chain(images, net, labels) for (images, labels), net in zip(train_ds, network)]

tf.Tensor(
[3139.8477 4048.7666 3749.6665 5590.043  4632.822  4924.8047 4476.5015
 4603.577  3537.6099 4072.5303 4767.435  5437.341  4763.8657 2366.0874
 5010.219  4912.016  3055.324  3647.8638 5080.977  4919.0713 2582.5908
 4221.676  4854.228  3849.9749 3967.531  5618.1704 3283.8342 3578.8572
 3633.5974 6110.093  2953.6045 3405.1284], shape=(32,), dtype=float32)
tf.Tensor(
[3139.8477 4048.7666 3749.6665 5590.043  4632.822  4924.8047 4476.5015
 4603.577  3537.6099 4072.5303 4767.435  5437.341  4763.8657 2366.0874
 5010.219  4912.016  3055.324  3647.8638 5080.977  4919.0713 2582.5908
 4221.676  4854.228  3849.9749 3967.531  5618.1704 3283.8342 3578.8572
 3633.5974 6110.093  2953.6045 3405.1284], shape=(32,), dtype=float32)
tf.Tensor(
[ -9509.298  -16191.705  -11273.2705 -24206.309  -10407.161  -22379.13
  -9342.936  -20912.7    -12840.11   -18211.863  -15977.278  -22488.895
 -15261.624   -4128.4473 -28708.498  -13236.141   -5998.7246 -16241.167
 -12036.891  -22674.594   -6132.739  -1091

tf.Tensor(
[ -8143.861 -13137.626 -69825.25  -19943.447 -61484.84  -18373.525
  -7752.357 -17645.953 -10454.202 -15243.797 -13186.51  -19114.676
 -12671.442 -28068.3   -24449.213 -10509.127 -41077.656 -13721.579
 -73206.805 -18683.828 -36669.08   -9261.537 -15896.793 -59162.4
 -53267.1   -21453.258  -8534.395 -70815.58  -42506.42  -26560.695
 -36219.684 -11416.796], shape=(32,), dtype=float32)
tf.Tensor(
[ -8143.861 -13137.626 -69825.25  -19943.447 -61484.84  -18373.525
  -7752.357 -17645.953 -10454.202 -15243.797 -13186.51  -19114.676
 -12671.442 -28068.3   -24449.213 -10509.127 -41077.656 -13721.579
 -73206.805 -18683.828 -36669.08   -9261.537 -15896.793 -59162.4
 -53267.1   -21453.258  -8534.395 -70815.58  -42506.42  -26560.695
 -36219.684 -11416.796], shape=(32,), dtype=float32)
tf.Tensor(
[ -41426.258  -65213.516 -109636.766  -96572.15  -100657.836  -88954.65
  -44385.01   -84287.24   -52448.07   -73310.34   -66997.875  -92788.375
  -64678.773  -44830.766 -112340.66   -57007.934  

tf.Tensor(
[  -6597.2124  -75417.49    -68074.57    -17208.604   -59573.387
 -109641.305   -53383.76    -14705.871   -62428.152   -80414.305
  -74725.57    -16059.192   -72909.48    -27490.424   -20575.35
  -67774.29    -39913.918   -79250.57    -71256.95    -15949.062
  -35654.242   -58776.08    -94103.72    -57683.992   -51839.375
  -18169.535    -6839.1035  -68773.07    -41112.28    -22509.2
  -35473.77    -66644.05  ], shape=(32,), dtype=float32)
tf.Tensor(
[  -6597.2124  -75417.49    -68074.57    -17208.604   -59573.387
 -109641.305   -53383.76    -14705.871   -62428.152   -80414.305
  -74725.57    -16059.192   -72909.48    -27490.424   -20575.35
  -67774.29    -39913.918   -79250.57    -71256.95    -15949.062
  -35654.242   -58776.08    -94103.72    -57683.992   -51839.375
  -18169.535    -6839.1035  -68773.07    -41112.28    -22509.2
  -35473.77    -66644.05  ], shape=(32,), dtype=float32)
tf.Tensor(
[ -35476.676 -121289.87  -102680.734  -84481.24   -93406.29  -171691.95
  -8504

tf.Tensor(
[ -67526.    -113595.52   -96267.11  -159668.19   -88177.1   -161048.83
  -79806.97  -136768.98   -93085.54  -122740.18  -113917.12  -147597.31
 -110362.32   -39634.766 -179767.77  -101818.08   -56761.082 -116196.03
 -104040.05   -68511.375  -51519.797  -86630.15  -139495.61   -82582.47
  -73636.59   -76309.45   -73319.18   -98252.07   -60438.613 -199782.86
  -51334.99   -98165.06 ], shape=(32,), dtype=float32)
tf.Tensor(
[ -67526.    -113595.52   -96267.11  -159668.19   -88177.1   -161048.83
  -79806.97  -136768.98   -93085.54  -122740.18  -113917.12  -147597.31
 -110362.32   -39634.766 -179767.77  -101818.08   -56761.082 -116196.03
 -104040.05   -68511.375  -51519.797  -86630.15  -139495.61   -82582.47
  -73636.59   -76309.45   -73319.18   -98252.07   -60438.613 -199782.86
  -51334.99   -98165.06 ], shape=(32,), dtype=float32)
tf.Tensor(
[ -42339.793  -72881.18   -66261.41  -100813.44   -58095.418 -106651.45
  -51989.406  -86235.49   -61140.176  -78024.42   -72656.74   -91

tf.Tensor(
[ -41267.266  -71282.33   -64922.973  -98166.81   -56920.824 -104141.45
  -50948.906  -84082.39   -59365.402  -76327.11   -70803.44   -89123.84
  -68931.17   -26191.125 -110191.76   -64644.793  -38231.59   -75530.414
  -67998.05   -80534.27   -33827.3    -55581.91   -89577.86   -55277.17
  -49691.414  -82662.33   -45258.12   -66164.805  -39208.668 -120885.78
  -33611.543  -63184.707], shape=(32,), dtype=float32)
tf.Tensor(
[ -41267.266  -71282.33   -64922.973  -98166.81   -56920.824 -104141.45
  -50948.906  -84082.39   -59365.402  -76327.11   -70803.44   -89123.84
  -68931.17   -26191.125 -110191.76   -64644.793  -38231.59   -75530.414
  -67998.05   -80534.27   -33827.3    -55581.91   -89577.86   -55277.17
  -49691.414  -82662.33   -45258.12   -66164.805  -39208.668 -120885.78
  -33611.543  -63184.707], shape=(32,), dtype=float32)
tf.Tensor(
[ -62609.824 -105133.984  -90409.52  -147636.17   -82221.016 -149995.14
  -74626.85  -127304.56   -86339.5   -114087.14  -105545.06  -1

tf.Tensor(
[ -40475.133  -70146.69   -64082.473  -96325.45   -55951.24  -102266.82
  -50052.426  -82480.08   -58714.76   -74805.555  -69438.61   -87494.68
  -67628.29   -25775.613 -107700.26   -63350.418  -37677.06   -74264.94
  -66821.16   -79105.53   -33189.97   -54688.953  -87922.26   -54374.684
  -48546.28   -80958.88   -44499.867  -65346.113  -38569.31  -117927.07
  -33243.543  -62074.83 ], shape=(32,), dtype=float32)
tf.Tensor(
[ -40475.133  -70146.69   -64082.473  -96325.45   -55951.24  -102266.82
  -50052.426  -82480.08   -58714.76   -74805.555  -69438.61   -87494.68
  -67628.29   -25775.613 -107700.26   -63350.418  -37677.06   -74264.94
  -66821.16   -79105.53   -33189.97   -54688.953  -87922.26   -54374.684
  -48546.28   -80958.88   -44499.867  -65346.113  -38569.31  -117927.07
  -33243.543  -62074.83 ], shape=(32,), dtype=float32)
tf.Tensor(
[ -59425.285 -100295.34   -86781.08  -140230.28   -78376.15  -142768.75
  -71057.836 -120856.36   -82987.56  -108210.55  -100199.74  -1

tf.Tensor(
[ -39834.34   -68832.03   -63064.234  -94752.055  -54950.113 -100695.94
  -49054.008  -80703.99   -57656.824  -73060.24   -68389.88   -85584.34
  -66509.27   -25382.531 -105431.09   -62448.08   -37086.31   -73006.27
  -65606.45   -77165.05   -32825.867  -53675.9    -86408.375  -53415.35
  -48144.504  -78500.695  -43324.89   -64057.203  -37797.41  -115896.45
  -32638.268  -61025.406], shape=(32,), dtype=float32)
tf.Tensor(
[ -56476.34   -95050.47   -82789.9   -133266.11   -74434.21  -136086.3
  -67231.06  -113978.62   -78794.84  -101808.89   -95405.09  -122397.56
  -92457.84   -33794.67  -149106.23   -85783.54   -48954.586  -98874.445
  -87859.29  -113373.14   -44141.44   -73484.54  -117921.555  -70721.54
  -63659.77  -118565.49   -60937.676  -83897.375  -51164.098 -165364.11
  -43566.99   -82798.484], shape=(32,), dtype=float32)
tf.Tensor(
[ -56476.34   -95050.47   -82789.9   -133266.11   -74434.21  -136086.3
  -67231.06  -113978.62   -78794.84  -101808.89   -95405.09  -1223

tf.Tensor(
[ -52578.297  -90078.234  -78997.484 -125260.16   -70497.8   -129238.66
  -63642.883 -107315.86   -74158.93   -96460.34   -89568.234 -114907.38
  -86979.04   -32434.012 -140789.81  -111175.195  -46585.074  -93462.375
  -83586.54  -105671.95   -41779.152  -69375.93  -111697.305  -67507.01
  -79088.54  -112163.01   -57777.57   -80319.86   -66675.16  -155130.72
  -41261.02   -78631.805], shape=(32,), dtype=float32)
tf.Tensor(
[ -52578.297  -90078.234  -78997.484 -125260.16   -70497.8   -129238.66
  -63642.883 -107315.86   -74158.93   -96460.34   -89568.234 -114907.38
  -86979.04   -32434.012 -140789.81  -111175.195  -46585.074  -93462.375
  -83586.54  -105671.95   -41779.152  -69375.93  -111697.305  -67507.01
  -79088.54  -112163.01   -57777.57   -80319.86   -66675.16  -155130.72
  -41261.02   -78631.805], shape=(32,), dtype=float32)
tf.Tensor(
[ -38488.492  -67495.83   -61956.89   -92302.58   -53737.875  -98704.38
  -48150.758  -78760.87   -56326.258  -71667.65   -66624.805  -

tf.Tensor(
[ -38114.516  -66224.59   -61282.93   -90711.83   -53149.84   -97371.95
  -47492.234  -77562.36   -75875.734  -70383.73   -65736.15   -82222.516
  -64061.29   -24650.021 -101176.37   -90269.06   -35867.51   -70481.83
  -63670.613  -73522.49   -43909.492  -51836.668  -83440.44   -51846.312
  -65027.44   -75051.82   -41718.492  -62303.22   -54413.188 -111082.086
  -43875.05   -59027.215], shape=(32,), dtype=float32)
tf.Tensor(
[ -38114.516  -66224.59   -61282.93   -90711.83   -53149.84   -97371.95
  -47492.234  -77562.36   -75875.734  -70383.73   -65736.15   -82222.516
  -64061.29   -24650.021 -101176.37   -90269.06   -35867.51   -70481.83
  -63670.613  -73522.49   -43909.492  -51836.668  -83440.44   -51846.312
  -65027.44   -75051.82   -41718.492  -62303.22   -54413.188 -111082.086
  -43875.05   -59027.215], shape=(32,), dtype=float32)
tf.Tensor(
[ -49870.652  -84829.47   -75437.02  -117835.78   -67104.81  -122639.99
  -60598.79  -101321.85   -90912.98   -90895.95   -84939.09

tf.Tensor(
[ -37612.156  -65334.97   -60526.938  -89421.09   -52399.22   -96131.664
  -46848.992  -76371.12   -75070.53   -69456.32   -64692.305  -80700.445
  -63084.51   -31778.666  -99724.51   -89789.36   -35539.71   -91775.72
  -83069.664  -72041.086  -43614.44   -51175.684  -82181.3    -65785.49
  -78157.555  -73267.11   -40979.75   -80586.734  -53846.957 -109457.6
  -43465.812  -77071.484], shape=(32,), dtype=float32)
tf.Tensor(
[ -47716.145  -81216.97   -72542.32  -112576.56   -64238.46  -117678.45
  -58032.016  -96606.73   -87831.46   -87004.68   -80964.945 -103009.734
  -78825.     -36938.902 -126232.336 -104168.78   -42763.023 -107585.27
  -96618.766  -93686.56   -50560.285  -63286.9   -101210.195  -76251.47
  -87567.72   -97540.41   -51590.49   -92725.836  -62009.633 -139518.61
  -50042.61   -90296.375], shape=(32,), dtype=float32)
tf.Tensor(
[ -47716.145  -81216.97   -72542.32  -112576.56   -64238.46  -117678.45
  -58032.016  -96606.73   -87831.46   -87004.68   -80964.945 -1

tf.Tensor(
[ -84604.78   -78709.71   -85712.17  -137507.44   -62204.895 -171207.45
  -55688.016  -92961.734  -85684.23   -84083.11   -78083.695  -99330.51
  -94446.375  -54288.203 -121709.516 -101610.36   -41443.906 -105001.7
  -94343.56   -90459.7    -58115.348  -60855.99   -98214.89   -74660.984
  -85906.805  -94112.836  -63330.633 -105214.46   -71642.66  -134213.73
  -56998.44   -88230.84 ], shape=(32,), dtype=float32)
tf.Tensor(
[ -75693.76   -64465.34   -75403.164 -117162.516  -51873.598 -152107.06
  -46074.918  -75377.33   -89289.     -68860.55   -63895.227  -79528.62
  -80697.58   -49829.24   -98495.35   -88890.57   -35054.566  -90879.516
  -82481.336  -71167.97   -60013.773  -64113.734  -81382.086  -77670.93
  -77754.07   -72269.95   -53797.453  -94572.11   -64371.23  -107965.75
  -58948.3    -76468.44 ], shape=(32,), dtype=float32)
tf.Tensor(
[ -75693.76   -64465.34   -75403.164 -117162.516  -51873.598 -152107.06
  -46074.918  -75377.33   -89289.     -68860.55   -63895.227  -7

tf.Tensor(
[ -75434.13   -80661.43   -74955.4   -116265.9    -63912.523 -151680.27
  -57209.883  -74651.18  -103248.91   -68313.92   -80446.49   -78887.27
  -80395.28   -60683.137  -97946.09  -103765.62   -50442.99   -90333.24
  -97505.89   -70638.61   -67217.59   -90528.414 -101639.234  -77307.95
  -87411.586  -71704.17   -65066.707  -94198.48   -64085.098 -107267.95
  -73333.805  -89915.14 ], shape=(32,), dtype=float32)
tf.Tensor(
[ -83215.29   -92870.59   -84157.83  -134055.3    -72984.17  -168624.23
  -65964.28   -90086.92  -113194.89   -82038.18   -93028.04   -95981.93
  -92592.53   -64683.02  -118627.01  -114685.01   -56076.5   -102303.695
 -108210.05   -87556.86   -72515.65   -99913.33  -116386.445  -85381.82
  -94763.37   -90684.81   -73427.28  -103533.516  -70408.25  -130565.46
  -78559.914 -100246.29 ], shape=(32,), dtype=float32)
tf.Tensor(
[ -83215.29   -92870.59   -84157.83  -134055.3    -72984.17  -168624.23
  -65964.28   -90086.92  -113194.89   -82038.18   -93028.04   -9

tf.Tensor(
[ -93953.28   -93232.195  -84091.805 -134477.56   -85016.31  -168343.69
  -77168.83  -132092.73  -112851.52   -81700.12  -109580.76  -119173.72
 -108888.375  -80534.68  -118342.016 -114659.55   -63131.883 -102579.85
 -107817.09  -110444.6    -79774.6    -99962.01  -116430.45   -85552.58
  -94729.24   -90971.71   -84974.87  -129428.03   -87253.68  -130508.57
  -78666.59  -114174.34 ], shape=(32,), dtype=float32)
tf.Tensor(
[ -86049.07   -80809.96   -75050.83  -116456.94   -76009.016 -151363.47
  -68655.09  -116497.695 -115990.9    -68037.04   -97304.76  -124797.17
  -96861.48   -76480.56   -97843.55  -103958.695  -57617.445  -90479.65
  -97479.55   -92952.79   -74644.03  -103235.17  -101803.32   -77460.24
  -87309.33   -71574.17   -76607.586 -119591.8    -80800.664 -107138.28
  -73394.86  -117741.23 ], shape=(32,), dtype=float32)
tf.Tensor(
[ -86049.07   -80809.96   -75050.83  -116456.94   -76009.016 -151363.47
  -68655.09  -116497.695 -115990.9    -68037.04   -97304.76  -124

tf.Tensor(
[ -86153.57   -80737.34   -99584.15  -116476.22   -88343.92  -151392.73
  -68648.87  -116417.54  -129614.01   -68115.14   -97256.49  -124929.3
  -96595.64   -81945.76  -125556.87  -103843.26   -57721.33  -106684.95
 -111513.01  -115621.19   -81560.61  -128521.875 -121455.17   -77360.875
 -107029.92   -97035.586  -76606.72  -119726.66   -89255.74  -138342.56
  -73290.22  -117549.305], shape=(32,), dtype=float32)
tf.Tensor(
[ -94097.35   -93021.414 -108834.99  -134476.53   -97579.945 -168050.25
  -77288.086 -132072.34  -139594.19   -81637.71  -110042.21  -142239.38
 -108599.53   -86000.18  -146173.62  -114839.42   -63409.734 -118911.44
 -122138.34  -132417.38   -86962.34  -137969.19  -136375.56   -85486.016
 -114320.49  -115911.64   -85040.68  -129205.29   -95689.32  -161414.3
  -78473.77  -127868.08 ], shape=(32,), dtype=float32)
tf.Tensor(
[ -94097.35   -93021.414 -108834.99  -134476.53   -97579.945 -168050.25
  -77288.086 -132072.34  -139594.19   -81637.71  -110042.21  -142

tf.Tensor(
[ -9769.81  -73697.8    -8532.805 -14336.163 -14399.54  -13210.859
 -14751.234 -19967.525 -16196.815 -12521.185 -51072.914  -9681.492
 -17514.688 -25380.324 -16121.459 -74229.81  -19676.93  -10443.469
 -16720.623 -50995.91  -43871.4   -84314.23  -71495.055 -20726.824
 -49999.88  -72040.95  -17631.209 -51637.855 -17691.16  -11928.761
 -58762.445 -87944.04 ], shape=(32,), dtype=float32)
tf.Tensor(
[ -9769.81  -73697.8    -8532.805 -14336.163 -14399.54  -13210.859
 -14751.234 -19967.525 -16196.815 -12521.185 -51072.914  -9681.492
 -17514.688 -25380.324 -16121.459 -74229.81  -19676.93  -10443.469
 -16720.623 -50995.91  -43871.4   -84314.23  -71495.055 -20726.824
 -49999.88  -72040.95  -17631.209 -51637.855 -17691.16  -11928.761
 -58762.445 -87944.04 ], shape=(32,), dtype=float32)
tf.Tensor(
[ -48648.32  -119975.67   -44107.17   -70808.53   -74128.555  -68266.2
  -75115.22   -93591.48   -80161.38   -64422.746  -80720.71   -54514.03
  -84558.42  -115250.984  -77715.77  -116977.17 

tf.Tensor(
[ -57660.78   -71927.74   -54303.047  -11638.289  -86868.82   -82403.94
  -91686.25   -16575.457  -13237.222  -77570.41   -49492.63   -67564.914
 -102354.18   -21576.123  -90516.15   -72406.414  -16371.382  -67953.32
  -14194.938  -49733.152  -42759.324  -82440.76   -69609.97   -17840.738
  -48691.93   -70014.09   -14774.258  -50300.324  -14930.888  -69537.23
  -57138.938  -85569.08 ], shape=(32,), dtype=float32)
tf.Tensor(
[ -91514.83  -112385.42   -85235.64   -60556.965 -139472.2   -130239.5
 -144640.73   -80414.055  -68714.75  -123073.97   -74974.98  -106870.08
 -160767.81   -99863.04  -144067.53  -109631.73   -78528.875 -107047.14
  -71111.36   -77142.59   -64611.54  -126280.734 -105679.32   -84238.41
  -74267.086 -107128.24   -72954.54   -77651.47   -72800.92  -112459.836
  -88911.53  -132688.88 ], shape=(32,), dtype=float32)
tf.Tensor(
[ -91514.83  -112385.42   -85235.64   -60556.965 -139472.2   -130239.5
 -144640.73   -80414.055  -68714.75  -123073.97   -74974.98  -10

tf.Tensor(
[ -84512.07  -104325.01   -79768.5   -110472.29  -128553.09  -121375.016
 -134291.23  -153506.61  -127603.02  -114492.9    -70175.54   -99931.34
 -149558.02  -176583.53  -133552.36  -102051.63   -66454.8    -99062.98
 -136072.95   -71920.62   -60487.547 -118037.26   -99087.76   -70807.74
  -69339.26   -99954.44  -133956.8    -71553.85  -138635.95  -103638.93
  -82430.125 -123113.07 ], shape=(32,), dtype=float32)
tf.Tensor(
[ -55574.18   -69468.195  -52998.055  -68145.57   -83782.15   -80015.2
  -88735.07   -98548.75   -80084.24   -75158.13   -48458.066  -65439.633
  -99280.32  -109320.805  -87525.89   -70378.61   -13162.213  -65555.07
  -87059.25   -48064.74   -41607.062  -79862.01   -67979.69   -14117.724
  -47491.27   -68111.36   -83706.43   -48525.62   -88860.234  -67123.734
  -55139.867  -83063.89 ], shape=(32,), dtype=float32)
tf.Tensor(
[ -55574.18   -69468.195  -52998.055  -68145.57   -83782.15   -80015.2
  -88735.07   -98548.75   -80084.24   -75158.13   -48458.066  -

tf.Tensor(
[ -54253.004  -68097.98   -51425.76   -65847.805  -81501.37   -78127.19
  -86939.555  -95481.12   -77928.72   -73125.18   -47275.434  -63795.855
  -97032.94  -106113.695  -85525.13   -68885.81   -76183.08   -64082.63
  -84961.445  -46983.992  -40755.26   -78085.01   -66304.29   -85337.06
  -46377.715  -66333.81   -81398.016  -47437.293  -86361.52   -65468.184
  -54171.066  -81243.86 ], shape=(32,), dtype=float32)
tf.Tensor(
[ -78205.39   -97014.2    -73485.19  -100895.68  -118662.57  -112477.26
 -124966.29  -141066.48  -117753.05  -105431.06   -65601.61   -91769.
 -138882.61  -161920.4   -123774.05   -95447.38  -120747.6    -91767.77
 -125968.4    -66362.875  -56367.973 -109125.14   -92119.39  -132756.27
  -64704.09   -92642.15  -122659.56   -66698.61  -127402.62   -96102.37
  -76865.125 -114964.125], shape=(32,), dtype=float32)
tf.Tensor(
[ -78205.39   -97014.2    -73485.19  -100895.68  -118662.57  -112477.26
 -124966.29  -141066.48  -117753.05  -105431.06   -65601.61   -91

tf.Tensor(
[ -74283.97   -91948.99   -69968.75   -95678.79  -112755.52  -106765.484
 -117746.734 -133252.31  -110231.445  -99540.64   -62558.324  -87171.69
 -130556.7   -152271.67  -116818.88   -90577.83  -112843.445  -87457.26
 -118516.516  -63251.84   -53814.016 -104125.125  -87692.97  -124320.72
  -61325.633  -88178.91  -115526.93   -63780.53  -120740.91   -90325.3
  -72386.375 -108880.484], shape=(32,), dtype=float32)
tf.Tensor(
[ -53203.688  -66533.64   -50211.695  -64163.65   -79788.85   -76229.96
  -85086.336  -93464.62   -76030.81   -71628.14   -46457.71   -62411.402
  -94652.29  -103079.88   -83690.81   -67630.41   -73510.87   -62811.543
  -82278.43   -46148.78   -40055.723  -76765.14   -64984.395  -83115.28
  -45451.473  -65135.96   -79714.68   -46725.523  -84657.26   -63902.383
  -52826.84   -79301.086], shape=(32,), dtype=float32)
tf.Tensor(
[ -53203.688  -66533.64   -50211.695  -64163.65   -79788.85   -76229.96
  -85086.336  -93464.62   -76030.81   -71628.14   -46457.71   

tf.Tensor(
[ -52078.113  -65318.98   -49416.17   -62671.855  -78187.914  -74600.6
  -83256.69   -91405.51   -74203.99   -70297.32   -45670.7    -61382.32
  -92883.35  -100932.46   -82127.61   -66203.984  -71980.52   -61649.156
  -80926.85   -45375.973  -39171.863  -75193.68   -63750.395  -81009.45
  -63163.06   -63929.016  -77909.87   -45741.926  -82689.35   -62230.766
  -51963.9    -78030.55 ], shape=(32,), dtype=float32)
tf.Tensor(
[ -52078.113  -65318.98   -49416.17   -62671.855  -78187.914  -74600.6
  -83256.69   -91405.51   -74203.99   -70297.32   -45670.7    -61382.32
  -92883.35  -100932.46   -82127.61   -66203.984  -71980.52   -61649.156
  -80926.85   -45375.973  -39171.863  -75193.68   -63750.395  -81009.45
  -63163.06   -63929.016  -77909.87   -45741.926  -82689.35   -62230.766
  -51963.9    -78030.55 ], shape=(32,), dtype=float32)
tf.Tensor(
[ -69475.5    -86221.08   -65444.402  -88138.52  -105215.984  -99207.49
 -110716.016 -124574.64  -103076.73   -93835.016  -59055.84   -

tf.Tensor(
[-51351.81  -64244.145 -48615.566 -61816.996 -77228.555 -73828.41
 -81962.68  -90132.53  -73014.54  -69385.21  -44870.01  -60457.496
 -91835.375 -99075.32  -80926.41  -65543.69  -70772.836 -60954.785
 -79607.34  -61517.22  -39005.168 -74624.086 -63132.523 -79411.32
 -62734.07  -63103.08  -76618.68  -45136.04  -81644.36  -61672.83
 -51257.832 -76928.42 ], shape=(32,), dtype=float32)
tf.Tensor(
[-51351.81  -64244.145 -48615.566 -61816.996 -77228.555 -73828.41
 -81962.68  -90132.53  -73014.54  -69385.21  -44870.01  -60457.496
 -91835.375 -99075.32  -80926.41  -65543.69  -70772.836 -60954.785
 -79607.34  -61517.22  -39005.168 -74624.086 -63132.523 -79411.32
 -62734.07  -63103.08  -76618.68  -45136.04  -81644.36  -61672.83
 -51257.832 -76928.42 ], shape=(32,), dtype=float32)
tf.Tensor(
[ -66508.23   -82268.43   -62450.836  -84192.11  -100930.07   -95504.555
 -105740.84  -119132.42   -98172.03   -89950.375  -56299.92   -78218.84
 -118274.4   -134173.7   -105187.25   -82273.1    -9

tf.Tensor(
[ -63587.02   -78765.76   -59874.07   -79339.59   -96270.13   -90881.71
 -101553.35  -113083.77   -93632.88   -85837.91   -54069.867  -74551.49
 -112835.484 -127736.87   -99944.89   -79069.836  -93213.87   -74872.76
 -100164.85   -71596.75   -46719.94   -90472.74   -76150.85  -103730.375
  -85745.445  -96312.336  -97194.3    -55197.008 -102239.734  -76981.53
  -79683.91   -93899.91 ], shape=(32,), dtype=float32)
tf.Tensor(
[ -63587.02   -78765.76   -59874.07   -79339.59   -96270.13   -90881.71
 -101553.35  -113083.77   -93632.88   -85837.91   -54069.867  -74551.49
 -112835.484 -127736.87   -99944.89   -79069.836  -93213.87   -74872.76
 -100164.85   -71596.75   -46719.94   -90472.74   -76150.85  -103730.375
  -85745.445  -96312.336  -97194.3    -55197.008 -102239.734  -76981.53
  -79683.91   -93899.91 ], shape=(32,), dtype=float32)
tf.Tensor(
[-50619.195 -63254.34  -48018.523 -60463.203 -75644.36  -72538.51
 -80833.24  -88243.47  -71706.41  -68187.49  -44342.082 -59423.594
 -

tf.Tensor(
[ -49734.21   -62627.3    -60834.11   -59566.957  -74893.586  -71725.86
  -79672.48  -116591.766  -70614.516  -67409.51   -43949.31   -77263.07
  -89398.45   -95803.14   -78601.37   -80808.48   -68098.11   -59100.895
 -102581.945  -60292.355  -58513.457  -72604.19   -61488.91   -76537.89
  -75126.88   -81352.7    -73919.71   -56404.707  -79141.734  -79337.42
  -66646.1   -121138.945], shape=(32,), dtype=float32)
tf.Tensor(
[ -49734.21   -62627.3    -60834.11   -59566.957  -74893.586  -71725.86
  -79672.48  -116591.766  -70614.516  -67409.51   -43949.31   -77263.07
  -89398.45   -95803.14   -78601.37   -80808.48   -68098.11   -59100.895
 -102581.945  -60292.355  -58513.457  -72604.19   -61488.91   -76537.89
  -75126.88   -81352.7    -73919.71   -56404.707  -79141.734  -79337.42
  -66646.1   -121138.945], shape=(32,), dtype=float32)
tf.Tensor(
[ -60370.65   -75558.2    -70748.35   -75438.836  -91730.07   -87158.43
  -96586.96  -137143.89   -88568.57   -82072.17   -52244.777  -

tf.Tensor(
[ -71855.984  -88515.78   -69065.38   -91254.586  -88712.28   -83965.45
 -134701.75  -133552.08   -85311.6    -96133.69   -60901.297  -87263.69
 -104103.664 -146857.92   -92297.23   -90626.22   -84342.53   -84093.984
 -138267.62   -67595.984  -64251.92   -83571.586  -70904.36   -93687.49
  -92781.125 -107022.61  -110919.58   -63402.355 -116545.336  -90459.16
  -86888.625 -133482.4  ], shape=(32,), dtype=float32)
tf.Tensor(
[ -62463.188  -77629.414  -60267.305  -77802.875  -74001.01   -70833.38
 -120267.484 -115574.93   -69667.055  -83508.6    -53754.344  -76627.36
  -88295.04  -125357.82   -77461.73   -80151.125  -66940.7    -73197.33
 -122488.984  -59926.46   -58138.926  -71771.305  -60917.414  -75506.64
  -85629.05   -96656.51   -94940.75   -65827.14  -100183.74   -94311.71
  -78041.97  -120315.72 ], shape=(32,), dtype=float32)
tf.Tensor(
[ -62463.188  -77629.414  -60267.305  -77802.875  -74001.01   -70833.38
 -120267.484 -115574.93   -69667.055  -83508.6    -53754.344  -7

tf.Tensor(
[ -74563.055  -77522.555  -71486.25   -95734.55   -73878.836  -70941.79
 -139791.44  -115420.64   -89782.586  -83425.77   -72063.93   -76454.04
  -88191.76  -153363.19   -96684.94   -79954.81  -111626.94   -73426.77
 -122540.81   -69772.164  -58024.2    -71916.13   -60909.594  -75536.34
  -94907.016  -96535.62  -115390.92   -65909.17  -141932.3   -109671.375
  -89272.67  -120142.445], shape=(32,), dtype=float32)
tf.Tensor(
[ -74563.055  -77522.555  -71486.25   -95734.55   -73878.836  -70941.79
 -139791.44  -115420.64   -89782.586  -83425.77   -72063.93   -76454.04
  -88191.76  -153363.19   -96684.94   -79954.81  -111626.94   -73426.77
 -122540.81   -69772.164  -58024.2    -71916.13   -60909.594  -75536.34
  -94907.016  -96535.62  -115390.92   -65909.17  -141932.3   -109671.375
  -89272.67  -120142.445], shape=(32,), dtype=float32)
tf.Tensor(
[ -83581.73   -88361.59   -79775.05  -109124.055  -87855.59   -83910.69
 -154292.3   -132539.44  -104873.5    -95759.3    -78992.77   -

tf.Tensor(
[ -95909.78   -88472.766  -79868.87  -108858.01  -106917.63  -101114.55
 -192016.36  -132480.2   -104797.734  -95725.48   -88442.88  -101705.29
 -103958.88  -174954.69  -111235.4    -90264.84  -150892.86   -83764.53
 -158538.64   -77130.234  -64280.87   -99332.836  -83287.     -93190.19
 -102048.805 -120065.6   -131079.62   -83131.25  -156933.81  -121162.1
  -98001.875 -132970.11 ], shape=(32,), dtype=float32)
tf.Tensor(
[ -95909.78   -88472.766  -79868.87  -108858.01  -106917.63  -101114.55
 -192016.36  -132480.2   -104797.734  -95725.48   -88442.88  -101705.29
 -103958.88  -174954.69  -111235.4    -90264.84  -150892.86   -83764.53
 -158538.64   -77130.234  -64280.87   -99332.836  -83287.     -93190.19
 -102048.805 -120065.6   -131079.62   -83131.25  -156933.81  -121162.1
  -98001.875 -132970.11 ], shape=(32,), dtype=float32)
tf.Tensor(
[ -86619.375  -77332.65   -71469.56   -95758.72   -92886.055  -88224.2
 -177040.92  -115539.625  -89612.64   -83401.51   -90791.     -91098

tf.Tensor(
[ -58704.652  -72904.875  -73902.164  -51517.64   -76899.29   -99709.2
  -94325.36   -47034.645  -19770.955  -77579.9    -70685.85   -35149.26
  -43911.31   -70204.82  -124284.62   -69523.65   -96475.375  -67474.76
  -49679.492  -56009.63   -46058.344  -88235.29   -53442.516 -131528.6
 -112140.914  -44310.63   -39667.02   -36048.402  -46759.863  -83860.08
  -92759.7    -99961.3  ], shape=(32,), dtype=float32)
tf.Tensor(
[ -58704.652  -72904.875  -73902.164  -51517.64   -76899.29   -99709.2
  -94325.36   -47034.645  -19770.955  -77579.9    -70685.85   -35149.26
  -43911.31   -70204.82  -124284.62   -69523.65   -96475.375  -67474.76
  -49679.492  -56009.63   -46058.344  -88235.29   -53442.516 -131528.6
 -112140.914  -44310.63   -39667.02   -36048.402  -46759.863  -83860.08
  -92759.7    -99961.3  ], shape=(32,), dtype=float32)
tf.Tensor(
[-11216.46   -44685.715  -14869.681   -9567.897  -15760.6045 -61486.46
 -57073.113   -8119.0425 -25118.691  -15773.136  -13911.886   -5798.22

tf.Tensor(
[-63227.55  -43365.67  -85159.97  -61432.56  -12834.531 -59560.277
 -55268.22  -56285.56  -24524.115 -12434.48  -76651.53  -42911.418
 -48531.805 -41702.254 -21881.322 -11258.555 -16044.532 -78490.1
 -60951.027 -64507.58  -52747.44  -15382.575 -31557.059 -22654.512
 -19510.799 -52560.023 -48581.164 -44157.22  -57079.273 -13887.135
 -55504.414 -16757.63 ], shape=(32,), dtype=float32)
tf.Tensor(
[-102089.36   -67410.81  -134247.72   -96073.68   -63802.68   -90902.195
  -85499.43   -88522.97   -38601.41   -64066.312 -123994.79   -67639.734
  -78502.625  -64629.227 -102468.88   -57254.992  -79388.68  -122370.65
  -94931.89  -102473.71   -83978.98   -73728.01   -48828.527 -108409.77
  -93124.36   -83910.39   -75394.46   -68826.914  -88404.99   -69247.47
  -85361.086  -82388.41 ], shape=(32,), dtype=float32)
tf.Tensor(
[-102089.36   -67410.81  -134247.72   -96073.68   -63802.68   -90902.195
  -85499.43   -88522.97   -38601.41   -64066.312 -123994.79   -67639.734
  -78502.625  -646

tf.Tensor(
[ -61494.023  -42080.727  -82947.26   -59947.168  -78457.13   -57973.53
  -53993.035  -55021.492  -23896.766  -74977.695  -74066.836  -41345.3
  -46729.08   -40507.402 -113950.03   -65192.605  -97219.805  -76265.69
  -59162.906  -62212.57   -51509.906  -88029.2    -30763.775  -19269.488
 -102793.41   -50737.684  -47266.66   -43049.83   -55620.445  -80536.11
  -53935.61   -90413.72 ], shape=(32,), dtype=float32)
tf.Tensor(
[ -94774.88   -62506.523 -124975.07   -89663.42  -122257.29   -84635.04
  -79967.734  -82814.6    -35962.83  -119224.49  -114170.85   -62046.523
  -71948.51   -59965.31  -183252.27  -104544.26  -151395.7   -113614.59
  -87996.484  -94146.38   -78421.83  -137697.     -45519.324  -93191.92
 -165723.17   -77190.08   -70109.56   -64156.97   -82370.48  -128065.97
  -79266.164 -146564.14 ], shape=(32,), dtype=float32)
tf.Tensor(
[ -94774.88   -62506.523 -124975.07   -89663.42  -122257.29   -84635.04
  -79967.734  -82814.6    -35962.83  -119224.49  -114170.85   -6

tf.Tensor(
[ -59798.344  -41003.363  -80753.29   -58483.695  -76084.83   -56889.996
  -52580.133  -53558.875  -23230.59   -73176.695  -72062.18   -40519.098
  -45590.234  -39680.137 -110385.16   -63554.203  -94894.52   -74583.586
  -58041.164  -60862.598  -50174.56   -85525.336  -30082.19  -114197.7
  -99434.44   -49517.875  -46286.363  -41952.62   -54235.105  -77886.79
  -52860.992  -87751.26 ], shape=(32,), dtype=float32)
tf.Tensor(
[ -88118.23   -58339.176 -116435.234  -83818.34  -113205.83   -79813.734
  -74591.695  -77173.89   -33458.305 -111289.19  -106197.83   -58351.516
  -67175.984  -56383.664 -169294.11   -97363.97  -141375.4   -106544.07
  -82883.914  -88265.875  -73108.11  -127755.96   -42707.883 -177127.33
 -152817.78   -72139.76   -65893.77   -59887.04   -76946.2   -118102.5
  -74626.51  -135747.8  ], shape=(32,), dtype=float32)
tf.Tensor(
[ -88118.23   -58339.176 -116435.234  -83818.34  -113205.83   -79813.734
  -74591.695  -77173.89   -33458.305 -111289.19  -106197.83  

tf.Tensor(
[ -83118.3    -55160.664 -110445.6    -79331.12  -106718.414  -75672.93
  -70583.61   -73066.03   -31580.62  -104313.164 -100425.336  -55117.3
  -63931.97   -53425.344 -159668.58   -91337.6   -132887.42  -100530.305
  -78135.19   -83764.22   -68625.11  -120709.43   -40387.938 -166340.89
 -143151.44   -68129.15   -62191.03   -57047.33   -72964.75  -111040.516
  -71057.78  -127091.27 ], shape=(32,), dtype=float32)
tf.Tensor(
[ -83118.3    -55160.664 -110445.6    -79331.12  -106718.414  -75672.93
  -70583.61   -73066.03   -31580.62  -104313.164 -100425.336  -55117.3
  -63931.97   -53425.344 -159668.58   -91337.6   -132887.42  -100530.305
  -78135.19   -83764.22   -68625.11  -120709.43   -40387.938 -166340.89
 -143151.44   -68129.15   -62191.03   -57047.33   -72964.75  -111040.516
  -71057.78  -127091.27 ], shape=(32,), dtype=float32)
tf.Tensor(
[ -58438.15   -40081.402  -79280.57   -57102.69   -74228.414  -55940.867
  -51603.617  -52338.867  -22684.998  -70719.41   -70705.27   

tf.Tensor(
[ -77952.9    -52096.453 -104842.664  -75253.555 -100250.69   -71936.47
  -67312.45   -68794.164  -29951.812  -97678.68   -94761.85   -52298.68
  -59661.68   -50384.273 -149211.66   -85441.67  -125227.266  -95410.39
  -74129.914  -78690.836  -64662.496 -113493.38   -38256.566 -155356.95
 -135138.81   -63891.137  -58924.547  -53959.727  -68914.47  -104636.97
  -66960.484 -119033.84 ], shape=(32,), dtype=float32)
tf.Tensor(
[ -57167.55   -39284.43   -77658.73   -56028.78   -72735.8    -54827.223
  -50692.016  -51240.66   -22235.098  -69459.336  -69076.09   -38876.027
  -43699.832  -38053.992 -105131.49   -60350.562  -90530.71   -71702.93
  -55683.92   -58362.977  -48196.355  -81839.94   -28943.482 -108177.47
  -94810.41   -47559.316  -44298.94   -40573.98   -52098.75   -74634.56
  -50841.195  -83294.39 ], shape=(32,), dtype=float32)
tf.Tensor(
[ -57167.55   -39284.43   -77658.73   -56028.78   -72735.8    -54827.223
  -50692.016  -51240.66   -22235.098  -69459.336  -69076.09   

tf.Tensor(
[ -56404.918  -38727.902  -76285.     -55195.13   -71439.94   -53905.035
  -50061.992  -50428.97   -21881.334  -68265.984  -67899.96   -38160.875
  -43019.195  -37451.16  -103172.14   -58996.223  -88977.36   -70619.66
  -54765.117  -57418.77   -47127.008  -80073.71   -28445.105 -106235.414
  -93002.06   -46676.41   -43934.83   -39679.973  -51638.21   -73056.65
  -50037.2    -81475.12 ], shape=(32,), dtype=float32)
tf.Tensor(
[ -56404.918  -38727.902  -76285.     -55195.13   -71439.94   -53905.035
  -50061.992  -50428.97   -21881.334  -68265.984  -67899.96   -38160.875
  -43019.195  -37451.16  -103172.14   -58996.223  -88977.36   -70619.66
  -54765.117  -57418.77   -47127.008  -80073.71   -28445.105 -106235.414
  -93002.06   -46676.41   -43934.83   -39679.973  -51638.21   -73056.65
  -50037.2    -81475.12 ], shape=(32,), dtype=float32)
tf.Tensor(
[ -74138.64   -49383.77   -98395.73   -70794.72   -94458.14   -68035.48
  -63946.344  -64927.29   -28180.195  -91865.08   -89159.66

tf.Tensor(
[ -70210.35   -59837.348  -94194.71   -67940.805  -89840.625  -65392.883
  -60557.69   -62167.965  -41471.426  -87019.66   -85020.62   -60639.676
  -53850.83   -59425.918 -132585.47   -75865.7   -111865.33   -86609.19
  -66969.695  -70998.47   -58763.08  -101627.31   -53975.113 -137454.42
 -119881.18   -57922.85   -53347.445  -48464.133  -62823.1    -93398.44
  -60859.95  -105706.125], shape=(32,), dtype=float32)
tf.Tensor(
[ -70210.35   -59837.348  -94194.71   -67940.805  -89840.625  -65392.883
  -60557.69   -62167.965  -41471.426  -87019.66   -85020.62   -60639.676
  -53850.83   -59425.918 -132585.47   -75865.7   -111865.33   -86609.19
  -66969.695  -70998.47   -58763.08  -101627.31   -53975.113 -137454.42
 -119881.18   -57922.85   -53347.445  -48464.133  -62823.1    -93398.44
  -60859.95  -105706.125], shape=(32,), dtype=float32)
tf.Tensor(
[ -55343.168  -50667.47   -75139.59   -54368.113  -70132.52   -53197.73
  -49037.605  -49638.855  -43335.89   -66869.51   -66664.67  

tf.Tensor(
[ -67161.58   -68851.6    -90589.81   -80466.07   -85985.92   -79222.93
  -58595.984  -59770.973  -47769.195  -82858.58  -103807.72   -69888.14
  -80416.66   -57675.086 -126275.09   -93447.086 -107167.34  -102715.52
  -81448.07   -68359.195  -55905.62   -97189.27   -68688.47  -130875.77
 -114038.875  -55373.42   -64984.07   -58788.08   -60297.8    -88973.05
  -58573.008 -129813.91 ], shape=(32,), dtype=float32)
tf.Tensor(
[ -54513.7    -60857.785  -74381.17   -69023.445  -69167.1    -68402.164
  -48531.062  -48927.715  -49359.754  -65977.75   -88373.08   -61862.297
  -70394.66   -49925.746  -99558.27   -78085.     -86335.64   -88149.
  -70077.03   -55951.98   -45803.137  -77654.66   -62787.387 -102426.01
  -89767.516  -58665.92   -56164.613  -50562.645  -50092.23   -70795.94
  -48804.832 -107540.86 ], shape=(32,), dtype=float32)
tf.Tensor(
[ -54513.7    -60857.785  -74381.17   -69023.445  -69167.1    -68402.164
  -48531.062  -48927.715  -49359.754  -65977.75   -88373.08   -6

tf.Tensor(
[ -53923.977  -89859.39   -73681.58   -68547.87   -68564.91   -93386.13
  -61040.676  -60925.49   -54524.234  -65207.367  -87413.17   -61676.617
  -82659.69   -68803.9    -98312.17   -77536.195  -85376.71   -87591.086
  -82356.86   -55319.266  -57434.715 -100735.69   -69420.1   -101148.79
  -88662.74   -69853.26   -55809.977  -81339.29   -74657.31   -92325.41
  -85951.01  -106833.734], shape=(32,), dtype=float32)
tf.Tensor(
[ -53923.977  -89859.39   -73681.58   -68547.87   -68564.91   -93386.13
  -61040.676  -60925.49   -54524.234  -65207.367  -87413.17   -61676.617
  -82659.69   -68803.9    -98312.17   -77536.195  -85376.71   -87591.086
  -82356.86   -55319.266  -57434.715 -100735.69   -69420.1   -101148.79
  -88662.74   -69853.26   -55809.977  -81339.29   -74657.31   -92325.41
  -85951.01  -106833.734], shape=(32,), dtype=float32)
tf.Tensor(
[ -64746.953  -96687.72   -87551.21   -78296.484  -82856.484 -102231.65
  -69490.29   -70050.016  -58503.652  -79802.766 -100441.62  

tf.Tensor(
[ -90637.59  -104106.45  -102523.62   -88997.95   -97962.23  -123155.04
  -78719.64   -91148.63   -58106.24   -95479.87   -99424.09   -77014.77
 -100134.19   -74696.234 -146316.08  -105692.42  -101105.86   -98601.875
 -102896.76   -90486.836  -76205.31  -115078.875  -93082.195 -122207.2
 -106737.45   -77678.97   -71351.95  -105055.17   -93017.29  -105917.03
 -104531.6   -123202.4  ], shape=(32,), dtype=float32)
tf.Tensor(
[ -90637.59  -104106.45  -102523.62   -88997.95   -97962.23  -123155.04
  -78719.64   -91148.63   -58106.24   -95479.87   -99424.09   -77014.77
 -100134.19   -74696.234 -146316.08  -105692.42  -101105.86   -98601.875
 -102896.76   -90486.836  -76205.31  -115078.875  -93082.195 -122207.2
 -106737.45   -77678.97   -71351.95  -105055.17   -93017.29  -105917.03
 -104531.6   -123202.4  ], shape=(32,), dtype=float32)
tf.Tensor(
[ -80922.61   -98017.516  -90040.72   -80148.02   -85286.586 -115094.766
  -71035.61   -83056.945  -54409.44   -82085.7    -87210.375  -7

tf.Tensor(
[ -80931.89   -98011.    -123527.96   -92153.695  -85401.445 -136760.47
  -71094.41   -83020.8    -73726.914  -82191.23   -87320.87   -87354.445
  -92908.086  -92085.91  -125505.82  -109428.94   -84550.18  -101641.69
 -117572.31  -106720.42   -99997.766 -100178.484  -88289.78  -100323.62
 -113014.12   -80367.74   -73463.88   -98414.17   -84911.37   -91833.48
  -96934.57  -128885.68 ], shape=(32,), dtype=float32)
tf.Tensor(
[ -80931.89   -98011.    -123527.96   -92153.695  -85401.445 -136760.47
  -71094.41   -83020.8    -73726.914  -82191.23   -87320.87   -87354.445
  -92908.086  -92085.91  -125505.82  -109428.94   -84550.18  -101641.69
 -117572.31  -106720.42   -99997.766 -100178.484  -88289.78  -100323.62
 -113014.12   -80367.74   -73463.88   -98414.17   -84911.37   -91833.48
  -96934.57  -128885.68 ], shape=(32,), dtype=float32)
tf.Tensor(
[ -90829.48  -104221.664 -136107.44  -100984.586  -98418.57  -144925.3
  -78904.164  -91366.08   -77376.164  -95488.99   -99425.54   -9

tf.Tensor(
[-103910.984 -104097.305 -136079.34  -113052.64   -98238.86  -155874.33
  -78684.43  -101754.09   -77306.95   -95114.78   -99150.414  -93667.05
 -111039.2    -98175.125 -172641.53  -121292.5   -100973.61  -112753.47
 -126346.44  -116201.65  -118864.69  -134471.1    -93118.56  -122042.72
 -131470.05   -98455.19   -89220.04  -104989.484  -93000.76  -106113.19
 -114894.414 -145530.6  ], shape=(32,), dtype=float32)
tf.Tensor(
[-103910.984 -104097.305 -136079.34  -113052.64   -98238.86  -155874.33
  -78684.43  -101754.09   -77306.95   -95114.78   -99150.414  -93667.05
 -111039.2    -98175.125 -172641.53  -121292.5   -100973.61  -112753.47
 -126346.44  -116201.65  -118864.69  -134471.1    -93118.56  -122042.72
 -131470.05   -98455.19   -89220.04  -104989.484  -93000.76  -106113.19
 -114894.414 -145530.6  ], shape=(32,), dtype=float32)
tf.Tensor(
[3204.799  3769.1077 4983.8325 2888.7578 2571.5269 3581.2427 3438.444
 4837.9956 4217.192  4732.749  4735.984  3907.1946 3830.6047 3888.8

tf.Tensor(
[-43682.07   -11214.817  -81865.234  -28060.584  -40537.355  -11514.097
 -59567.316  -10450.062  -53826.133  -13121.23   -59649.59    -5539.5957
 -48731.914  -11429.07   -93200.79   -99836.06   -73748.23   -12847.857
 -15234.354  -62065.67    -8326.591   -7609.464  -15598.005  -35989.81
 -26200.113  -10737.147  -81465.77   -21532.139  -22972.076  -12916.848
 -15804.494   -7664.851 ], shape=(32,), dtype=float32)
tf.Tensor(
[-43682.07   -11214.817  -81865.234  -28060.584  -40537.355  -11514.097
 -59567.316  -10450.062  -53826.133  -13121.23   -59649.59    -5539.5957
 -48731.914  -11429.07   -93200.79   -99836.06   -73748.23   -12847.857
 -15234.354  -62065.67    -8326.591   -7609.464  -15598.005  -35989.81
 -26200.113  -10737.147  -81465.77   -21532.139  -22972.076  -12916.848
 -15804.494   -7664.851 ], shape=(32,), dtype=float32)
tf.Tensor(
[ -69618.79   -56266.605 -128458.125  -44586.668  -64801.418  -56806.26
  -93544.28   -56330.055  -86594.62   -66631.74   -95671.89   -34

tf.Tensor(
[ -65708.57  -107227.64  -119959.516  -41852.96   -60565.266 -107443.07
  -87718.54  -106785.734  -80759.91   -57144.01   -89255.48   -66533.95
  -73202.09  -111939.445 -138669.53  -146756.39  -112020.06  -126396.39
  -60496.56   -91262.44   -87175.96   -81084.97  -147668.95   -53826.4
 -224496.08  -101130.375 -123405.3    -85371.33   -92577.84  -120610.2
 -144733.36   -80579.31 ], shape=(32,), dtype=float32)
tf.Tensor(
[ -65708.57  -107227.64  -119959.516  -41852.96   -60565.266 -107443.07
  -87718.54  -106785.734  -80759.91   -57144.01   -89255.48   -66533.95
  -73202.09  -111939.445 -138669.53  -146756.39  -112020.06  -126396.39
  -60496.56   -91262.44   -87175.96   -81084.97  -147668.95   -53826.4
 -224496.08  -101130.375 -123405.3    -85371.33   -92577.84  -120610.2
 -144733.36   -80579.31 ], shape=(32,), dtype=float32)
tf.Tensor(
[ -42414.566  -68024.63   -79767.43   -27379.693  -39210.445  -67612.33
  -57854.324  -65794.984  -52036.16   -10268.874  -57760.254  -41276.

tf.Tensor(
[ -41217.125  -66063.086  -77360.59   -26665.059  -38230.68   -65714.49
  -56488.48   -63718.234  -50995.363  -67143.195  -56242.465  -40100.53
  -45755.395  -68601.8    -87973.62   -94282.75   -69294.57   -75374.19
  -67517.15   -59092.41   -52749.65   -49578.473  -88683.125  -33956.43
 -134136.28   -59861.914  -77015.305  -14606.213  -98492.23   -73824.49
  -88440.43   -49125.887], shape=(32,), dtype=float32)
tf.Tensor(
[ -41217.125  -66063.086  -77360.59   -26665.059  -38230.68   -65714.49
  -56488.48   -63718.234  -50995.363  -67143.195  -56242.465  -40100.53
  -45755.395  -68601.8    -87973.62   -94282.75   -69294.57   -75374.19
  -67517.15   -59092.41   -52749.65   -49578.473  -88683.125  -33956.43
 -134136.28   -59861.914  -77015.305  -14606.213  -98492.23   -73824.49
  -88440.43   -49125.887], shape=(32,), dtype=float32)
tf.Tensor(
[ -59936.18   -98945.27  -110991.96   -38761.145  -55768.88   -98730.3
  -81173.64   -97179.53   -74964.67  -106532.39   -82277.23   -613

tf.Tensor(
[ -56571.266  -92312.48  -104295.08   -36529.55   -51984.836  -92793.74
  -76427.69   -90961.92   -69703.27   -98134.74   -77043.805  -57032.117
  -63581.223  -96398.27  -120106.67  -127663.63   -96039.41  -107459.055
  -99424.625  -79846.41   -75216.17   -68806.13  -125587.89   -46608.156
 -191907.08   -85518.375 -106401.22  -127401.85  -148328.17  -103426.52
 -124542.74   -69552.59 ], shape=(32,), dtype=float32)
tf.Tensor(
[ -40201.74   -64266.617  -75687.5    -26164.74   -37247.434  -63813.145
  -55274.734  -62218.574  -49434.137  -65035.266  -55330.836  -38932.266
  -44422.473  -66787.016  -85624.73   -92369.16   -67495.414  -73124.836
  -65492.57   -57748.453  -51469.53   -48193.055  -86032.89   -33243.957
 -130318.836  -58177.883  -74886.484  -78593.445  -95186.66   -71601.09
  -86304.52   -47912.562], shape=(32,), dtype=float32)
tf.Tensor(
[ -40201.74   -64266.617  -75687.5    -26164.74   -37247.434  -63813.145
  -55274.734  -62218.574  -49434.137  -65035.266  -55330.

tf.Tensor(
[ -39538.637  -62974.965  -74163.49   -25379.324  -36411.523  -62263.99
  -54071.44   -60577.72   -48553.527  -63228.258  -53715.38   -38029.195
  -43737.316  -65543.875  -84166.375  -90498.96   -66314.31   -71568.97
  -63648.418  -56750.21   -50497.465  -47010.555  -84193.57   -32643.541
 -127071.27   -56782.51   -73345.01   -76126.4    -92974.94   -70276.97
  -84295.16   -46773.824], shape=(32,), dtype=float32)
tf.Tensor(
[ -39538.637  -62974.965  -74163.49   -25379.324  -36411.523  -62263.99
  -54071.44   -60577.72   -48553.527  -63228.258  -53715.38   -38029.195
  -43737.316  -65543.875  -84166.375  -90498.96   -66314.31   -71568.97
  -63648.418  -56750.21   -50497.465  -47010.555  -84193.57   -32643.541
 -127071.27   -56782.51   -73345.01   -76126.4    -92974.94   -70276.97
  -84295.16   -46773.824], shape=(32,), dtype=float32)
tf.Tensor(
[ -52968.754  -86472.07   -98116.92   -33857.01   -48754.168  -85491.695
  -71601.58   -84462.72   -65511.65   -91196.914  -72196.02 

tf.Tensor(
[ -38768.137  -61977.71   -73219.266  -35270.43   -36048.785  -61370.32
  -53339.434  -59402.934  -47615.574  -61749.582  -52943.223  -37061.01
  -42913.66   -64347.793  -82704.3    -89197.766  -64945.508  -70065.87
  -62128.977  -55858.93   -49754.8    -45834.63   -82825.14   -45166.707
 -124636.516  -55621.992  -72121.94   -74053.516  -90911.42   -69036.22
  -83008.305  -45887.51 ], shape=(32,), dtype=float32)
tf.Tensor(
[ -38768.137  -61977.71   -73219.266  -35270.43   -36048.785  -61370.32
  -53339.434  -59402.934  -47615.574  -61749.582  -52943.223  -37061.01
  -42913.66   -64347.793  -82704.3    -89197.766  -64945.508  -70065.87
  -62128.977  -55858.93   -49754.8    -45834.63   -82825.14   -45166.707
 -124636.516  -55621.992  -72121.94   -74053.516  -90911.42   -69036.22
  -83008.305  -45887.51 ], shape=(32,), dtype=float32)
tf.Tensor(
[ -50104.84   -82167.164  -93868.125  -42779.062  -46811.742  -81396.96
  -68408.14   -79758.47   -61971.84   -85500.25   -68813.94   -

tf.Tensor(
[ -38304.684  -60920.18   -96208.11   -44238.348  -35501.957  -60599.965
  -52653.566  -58296.297  -47040.777  -60596.14   -71582.336  -36568.52
  -42388.867  -63572.035  -81585.31   -88186.51   -64028.15   -69183.05
  -61203.22   -54991.26   -48579.67   -45335.28   -81563.74   -56080.863
 -122763.51   -54985.105  -71386.805  -72741.484  -89036.5    -68020.586
  -81689.17   -45210.004], shape=(32,), dtype=float32)
tf.Tensor(
[ -48184.344  -78319.97  -113932.62   -50656.72   -44782.805  -78102.73
  -65738.41   -75777.68   -59565.77   -81126.97   -85538.32   -47628.55
  -54065.145  -81764.01  -102507.81  -110096.69   -81767.92   -90292.7
  -82305.75   -68534.77   -62755.48   -58464.23  -105889.34   -64470.93
 -160495.22   -72108.99   -90871.38  -102856.82  -121386.17   -87562.27
 -105320.19   -58486.848], shape=(32,), dtype=float32)
tf.Tensor(
[ -48184.344  -78319.97  -113932.62   -50656.72   -44782.805  -78102.73
  -65738.41   -75777.68   -59565.77   -81126.97   -85538.32   -

tf.Tensor(
[ -63893.336  -60179.594 -116552.05   -52576.848  -35071.93   -59676.207
  -51963.516  -57518.668  -46461.06   -59638.617  -70734.11   -35999.215
  -41692.53   -62674.63   -80745.664  -86900.766  -63115.484  -68064.5
  -60064.203  -54356.97   -48076.566  -60599.78   -80358.46   -65479.617
 -121269.6    -54051.04   -70266.625  -70902.3    -87362.58   -67010.81
  -80407.11   -44364.395], shape=(32,), dtype=float32)
tf.Tensor(
[ -72347.266  -75117.65  -131596.83   -58210.01   -43017.586  -74540.39
  -63074.13   -72491.21   -57177.34   -77189.87   -82472.13   -45393.73
  -51524.85   -78201.69   -98753.78  -105364.38   -78189.08   -85982.95
  -77958.695  -65934.945  -60339.32   -71991.95  -101088.875  -72577.234
 -153778.61   -68560.98   -86726.38   -96236.2   -114844.08   -83625.6
 -100436.32   -55488.07 ], shape=(32,), dtype=float32)
tf.Tensor(
[ -72347.266  -75117.65  -131596.83   -58210.01   -43017.586  -74540.39
  -63074.13   -72491.21   -57177.34   -77189.87   -82472.13   -

tf.Tensor(
[ -70905.76  -107798.33  -147648.55   -56899.566  -41205.25   -90603.76
  -73785.94   -69741.2    -55073.688  -94540.945  -80366.12   -43770.984
  -75674.75   -74587.48  -118435.15  -101985.14   -92360.39  -106290.266
  -95834.13   -63870.914  -57725.05   -82404.94   -97087.08   -88959.086
 -147211.53   -84853.81   -83490.68   -91208.07  -109694.42   -80454.42
 -120448.14   -53481.234], shape=(32,), dtype=float32)
tf.Tensor(
[ -63578.617  -94970.46  -134242.98   -52149.02   -43375.645  -77709.65
  -64373.348  -56918.758  -45780.754  -79293.23   -70188.79   -35519.56
  -66799.875  -61585.066 -102859.37   -86043.16   -79703.73   -90912.88
  -79798.84   -53569.88   -47521.95   -73051.37   -79287.52   -82940.4
 -119449.125  -72246.516  -69320.35   -69810.305  -86052.664  -65980.2
 -103225.67   -43890.234], shape=(32,), dtype=float32)
tf.Tensor(
[ -63578.617  -94970.46  -134242.98   -52149.02   -43375.645  -77709.65
  -64373.348  -56918.758  -45780.754  -79293.23   -70188.79   -3

tf.Tensor(
[ -63361.008 -110460.805 -149385.44   -57459.137  -51434.5    -77004.94
  -76436.42   -56146.137  -45423.98   -78631.516  -69717.766  -55614.305
  -76967.945  -92759.195 -119605.98  -122492.734  -96187.53  -107620.72
  -79262.17   -64237.63   -59000.914  -83166.41   -78411.66  -105050.67
 -118037.16   -71553.94  -103388.45   -68625.93   -84928.19   -65300.234
 -122177.72   -66970.445], shape=(32,), dtype=float32)
tf.Tensor(
[ -63361.008 -110460.805 -149385.44   -57459.137  -51434.5    -77004.94
  -76436.42   -56146.137  -45423.98   -78631.516  -69717.766  -55614.305
  -76967.945  -92759.195 -119605.98  -122492.734  -96187.53  -107620.72
  -79262.17   -64237.63   -59000.914  -83166.41   -78411.66  -105050.67
 -118037.16   -71553.94  -103388.45   -68625.93   -84928.19   -65300.234
 -122177.72   -66970.445], shape=(32,), dtype=float32)
tf.Tensor(
[ -69636.58  -121142.484 -160177.48   -61378.59   -57125.36   -87700.234
  -84456.93   -66852.23   -53054.414  -91181.336  -78170.23 

tf.Tensor(
[ -79490.63  -110544.71  -164301.45   -62833.84   -51350.652 -119406.68
  -87034.664  -70279.49   -65881.984  -78741.96  -103706.56   -74098.57
  -86189.47  -136656.22  -119595.57  -122338.58   -96066.61  -107826.48
  -96682.555  -86132.44   -70546.875  -93988.48   -78435.99  -119529.1
 -149087.44   -71759.72  -103396.516  -68502.78   -84908.45   -81046.76
 -122156.09   -88481.9  ], shape=(32,), dtype=float32)
tf.Tensor(
[ -79490.63  -110544.71  -164301.45   -62833.84   -51350.652 -119406.68
  -87034.664  -70279.49   -65881.984  -78741.96  -103706.56   -74098.57
  -86189.47  -136656.22  -119595.57  -122338.58   -96066.61  -107826.48
  -96682.555  -86132.44   -70546.875  -93988.48   -78435.99  -119529.1
 -149087.44   -71759.72  -103396.516  -68502.78   -84908.45   -81046.76
 -122156.09   -88481.9  ], shape=(32,), dtype=float32)
tf.Tensor(
[ -85633.234 -121309.73  -175376.47   -66819.42   -56958.574 -130014.19
  -95099.24   -81176.5    -73521.914  -91403.38  -112219.914  -8100

tf.Tensor(
[ -93658.18  -135136.52  -190086.62   -67024.83   -64390.88  -130365.97
 -105721.805  -95361.9    -73667.86   -91272.53  -123599.97   -90234.43
  -93339.83  -162783.08  -132647.47  -153674.62  -136451.86  -120757.86
 -109429.555  -94562.33  -103067.92  -101925.33  -132915.42  -124828.11
 -203173.8    -81906.6   -115289.35   -86998.28  -104127.555  -92795.516
 -136620.19  -118516.01 ], shape=(32,), dtype=float32)
tf.Tensor(
[ -87556.08  -124799.625 -178917.39   -62832.145  -58854.    -119407.43
  -97577.97   -84676.46   -65987.91   -78575.47  -114978.26   -83105.94
  -86270.9   -151690.3   -119639.63  -140111.66  -125305.37  -107782.31
  -96559.34   -86199.33   -94303.875  -94001.7   -118356.16  -119428.73
 -180093.89   -71579.914 -103530.47   -68785.53   -84884.22   -81052.66
 -122313.664 -110531.375], shape=(32,), dtype=float32)
tf.Tensor(
[ -87556.08  -124799.625 -178917.39   -62832.145  -58854.    -119407.43
  -97577.97   -84676.46   -65987.91   -78575.47  -114978.26   -8

tf.Tensor(
[ -91752.195  -63350.094  -36989.617  -68958.03  -104973.63   -84035.47
 -102589.69   -42330.113  -44811.465  -45719.09   -83410.52   -40814.37
  -85043.086 -127437.91  -120948.484  -54556.984  -59465.324  -71832.695
  -93190.84   -78998.74   -82336.84   -41231.6    -69391.51   -62022.914
 -119401.22  -101340.86   -57715.785 -130829.234  -60091.086  -68751.484
 -102817.19  -136534.7  ], shape=(32,), dtype=float32)
tf.Tensor(
[ -91752.195  -63350.094  -36989.617  -68958.03  -104973.63   -84035.47
 -102589.69   -42330.113  -44811.465  -45719.09   -83410.52   -40814.37
  -85043.086 -127437.91  -120948.484  -54556.984  -59465.324  -71832.695
  -93190.84   -78998.74   -82336.84   -41231.6    -69391.51   -62022.914
 -119401.22  -101340.86   -57715.785 -130829.234  -60091.086  -68751.484
 -102817.19  -136534.7  ], shape=(32,), dtype=float32)
tf.Tensor(
[-18821.607 -12444.389 -47105.844 -13608.507 -64184.258 -16362.314
 -19829.93  -53733.87   -8494.806  -8644.012 -16863.72   -7144.0

tf.Tensor(
[ -97119.2    -71133.64   -45817.65   -81463.42   -62549.33   -90869.75
 -109808.52   -52206.42   -51887.2    -54644.516  -90888.07   -48818.71
  -13747.495  -21281.17   -21150.744  -59105.05    -9464.104  -11741.05
  -15279.481  -89587.51   -90789.65   -24479.73   -77707.195   -9408.39
  -19687.348  -17318.934   -9551.568  -78147.266  -73509.195  -40926.18
  -18087.152  -23321.463], shape=(32,), dtype=float32)
tf.Tensor(
[ -97119.2    -71133.64   -45817.65   -81463.42   -62549.33   -90869.75
 -109808.52   -52206.42   -51887.2    -54644.516  -90888.07   -48818.71
  -13747.495  -21281.17   -21150.744  -59105.05    -9464.104  -11741.05
  -15279.481  -89587.51   -90789.65   -24479.73   -77707.195   -9408.39
  -19687.348  -17318.934   -9551.568  -78147.266  -73509.195  -40926.18
  -18087.152  -23321.463], shape=(32,), dtype=float32)
tf.Tensor(
[-158292.03  -113875.06   -72147.77  -127397.8    -96443.586 -147935.12
 -179055.11   -81577.53   -82272.81   -85419.57  -146288.19   -76

tf.Tensor(
[-146193.67  -105978.445  -66669.57  -118948.55   -89068.71  -136799.73
 -165160.8    -75296.29   -76154.34   -79051.8   -135316.83   -71356.57
 -132396.48  -200474.52   -84648.62   -87557.97   -91544.7   -108328.98
 -140180.3   -131735.38  -134001.1    -35412.62  -115548.13   -94001.43
  -83443.37   -70603.85   -90466.32  -112276.86  -106945.25   -58810.402
  -73200.72   -94588.97 ], shape=(32,), dtype=float32)
tf.Tensor(
[-146193.67  -105978.445  -66669.57  -118948.55   -89068.71  -136799.73
 -165160.8    -75296.29   -76154.34   -79051.8   -135316.83   -71356.57
 -132396.48  -200474.52   -84648.62   -87557.97   -91544.7   -108328.98
 -140180.3   -131735.38  -134001.1    -35412.62  -115548.13   -94001.43
  -83443.37   -70603.85   -90466.32  -112276.86  -106945.25   -58810.402
  -73200.72   -94588.97 ], shape=(32,), dtype=float32)
tf.Tensor(
[ -94155.21   -69030.695  -44052.92   -78996.54   -60520.453  -87954.75
 -106087.74   -50261.715  -50491.848  -52686.96   -88530.91   -

tf.Tensor(
[ -91697.17   -67152.945  -43433.492  -77526.26   -59309.234  -85333.484
 -103229.47   -49536.234  -49094.973  -51867.68   -86049.375  -46378.355
  -81932.63  -125254.97  -100506.875  -55913.258  -56039.164  -65608.68
  -84801.84   -84784.42   -85944.914  -23383.78   -73211.85   -56919.805
  -97527.4    -77966.07   -56208.01   -74726.74   -69922.94   -38808.8
  -85375.03  -105443.33 ], shape=(32,), dtype=float32)
tf.Tensor(
[-136197.03   -98090.164  -62575.457 -111107.14   -83796.516 -126437.08
 -153270.1    -70903.29   -71132.95   -74236.234 -126470.336  -66535.414
 -122931.67  -186233.9   -158259.11   -81776.12   -84953.72  -100082.32
 -130104.22  -123003.625 -125704.95   -33123.977 -107340.05   -87017.99
 -155395.44  -126886.23   -84363.266 -105542.18   -99616.32   -54719.363
 -134214.92  -170037.25 ], shape=(32,), dtype=float32)
tf.Tensor(
[-136197.03   -98090.164  -62575.457 -111107.14   -83796.516 -126437.08
 -153270.1    -70903.29   -71132.95   -74236.234 -126470.336 

tf.Tensor(
[-127627.25   -92100.15   -58649.746 -104914.984  -78953.87  -118562.94
 -143866.05   -66349.6    -66786.375  -69781.695 -118189.484  -62847.277
 -114823.13  -174226.56  -146055.39   -76994.77   -78789.71   -93788.01
 -120843.41  -115425.41  -117386.945  -31067.818 -100627.66   -80641.46
 -143226.25  -117085.53   -78408.08   -98786.96   -93751.65   -51574.74
 -124877.92  -157837.42 ], shape=(32,), dtype=float32)
tf.Tensor(
[-127627.25   -92100.15   -58649.746 -104914.984  -78953.87  -118562.94
 -143866.05   -66349.6    -66786.375  -69781.695 -118189.484  -62847.277
 -114823.13  -174226.56  -146055.39   -76994.77   -78789.71   -93788.01
 -120843.41  -115425.41  -117386.945  -31067.818 -100627.66   -80641.46
 -143226.25  -117085.53   -78408.08   -98786.96   -93751.65   -51574.74
 -124877.92  -157837.42 ], shape=(32,), dtype=float32)
tf.Tensor(
[ -89155.32   -65739.664  -42351.625  -75647.13   -58074.98   -83423.02
 -100559.195  -48355.715  -47913.656  -50524.656  -83885.55   -

tf.Tensor(
[-120333.43   -86928.37   -55530.363  -98427.81   -74738.195 -112125.01
 -135410.12   -62994.004  -62940.527  -66039.84  -111453.37   -59455.45
 -108246.25  -164602.16  -136446.05   -72806.44   -73889.99   -87524.35
 -113327.83  -109083.44  -110904.54   -29643.371  -95153.65   -76177.13
 -134409.36  -108855.11   -73800.29   -94054.26   -89169.42   -49246.33
 -116968.5   -146406.58 ], shape=(32,), dtype=float32)
tf.Tensor(
[-120333.43   -86928.37   -55530.363  -98427.81   -74738.195 -112125.01
 -135410.12   -62994.004  -62940.527  -66039.84  -111453.37   -59455.45
 -108246.25  -164602.16  -136446.05   -72806.44   -73889.99   -87524.35
 -113327.83  -109083.44  -110904.54   -29643.371  -95153.65   -76177.13
 -134409.36  -108855.11   -73800.29   -94054.26   -89169.42   -49246.33
 -116968.5   -146406.58 ], shape=(32,), dtype=float32)
tf.Tensor(
[ -87307.23   -64342.38   -41446.63   -74140.68   -57083.543  -81705.26
  -98669.75   -47491.348  -46854.055  -49650.28   -81910.83   -44

tf.Tensor(
[-114032.38   -82314.734  -53020.812  -93629.3    -71294.54  -105653.766
 -127719.266  -60007.92   -59732.04   -62692.32  -106030.53   -56425.016
 -102708.26  -155797.64  -128628.08   -68562.664  -70048.1    -82872.14
 -106309.914 -103552.234 -105430.02   -45884.793  -90074.25   -71022.97
 -125654.08  -101768.74   -69815.31   -89387.9    -84375.26   -46915.133
 -109360.04  -137517.31 ], shape=(32,), dtype=float32)
tf.Tensor(
[-114032.38   -82314.734  -53020.812  -93629.3    -71294.54  -105653.766
 -127719.266  -60007.92   -59732.04   -62692.32  -106030.53   -56425.016
 -102708.26  -155797.64  -128628.08   -68562.664  -70048.1    -82872.14
 -106309.914 -103552.234 -105430.02   -45884.793  -90074.25   -71022.97
 -125654.08  -101768.74   -69815.31   -89387.9    -84375.26   -46915.133
 -109360.04  -137517.31 ], shape=(32,), dtype=float32)
tf.Tensor(
[ -86013.     -63201.246  -40863.953  -73092.625  -56083.793  -80129.68
  -96816.56   -46587.992  -46080.164  -48765.83   -80767.83

tf.Tensor(
[-108305.68   -78670.79   -50342.76   -89814.59   -68275.53  -100837.336
 -122016.04   -57212.875  -57362.4    -76470.11  -100852.63   -70846.695
  -97070.03  -147892.78  -121706.914  -65518.2    -66390.85   -78628.164
 -101273.34   -98728.44  -100444.57   -44667.715  -85916.4    -67872.055
 -118325.98   -95751.836  -66305.1    -86062.73   -81488.74   -57144.07
 -103606.664 -129782.06 ], shape=(32,), dtype=float32)
tf.Tensor(
[ -84636.35   -62474.01   -40272.586  -72055.59   -55274.78   -78875.7
  -95315.19   -60796.832  -45524.96   -64646.594  -79361.11   -59990.95
  -75512.61  -115705.23   -90924.44   -51737.02   -51254.35   -60214.65
  -76914.75   -78592.2    -79326.76   -46504.43   -67717.06   -52206.59
  -88033.94   -69914.65   -51535.79   -69686.26   -65168.67   -48483.74
  -77402.84   -94871.71 ], shape=(32,), dtype=float32)
tf.Tensor(
[ -84636.35   -62474.01   -40272.586  -72055.59   -55274.78   -78875.7
  -95315.19   -60796.832  -45524.96   -64646.594  -79361.11   -

tf.Tensor(
[ -83482.06   -80144.266  -52183.133  -90995.57   -54702.434  -77753.99
 -127948.84   -73025.75   -44835.99   -63852.13   -78446.11   -59381.67
  -74336.08  -113669.99   -89518.586  -51007.496  -50400.594  -80513.555
  -76141.8    -77600.7   -101225.734  -46104.43   -89954.445  -51107.633
  -86595.35   -68508.734  -50864.9    -88750.1    -64355.137  -57333.188
  -76202.516  -92952.2  ], shape=(32,), dtype=float32)
tf.Tensor(
[-102890.6    -93682.1    -60400.5   -105524.7    -65333.332  -95620.74
 -149752.62   -82373.02   -54281.445  -73509.74   -95973.96   -68207.92
  -92199.516 -139969.11  -114581.21   -62149.164  -62811.965  -95443.234
  -95798.35   -94169.58  -118381.664  -50403.09  -104825.95   -64023.523
 -111741.22   -89585.16   -63074.867 -101978.1    -77209.05   -64340.215
  -97342.67  -120630.336], shape=(32,), dtype=float32)
tf.Tensor(
[-102890.6    -93682.1    -60400.5   -105524.7    -65333.332  -95620.74
 -149752.62   -82373.02   -54281.445  -73509.74   -95973.96

tf.Tensor(
[ -82766.95   -97640.41   -62512.562  -90434.87   -68457.695  -76954.414
 -127042.43   -72617.484  -56424.71   -63397.965  -98442.74   -70337.3
 -116980.734 -112895.17   -88298.125  -50682.305  -81030.766  -79713.78
  -75216.71   -76905.266 -100491.97   -57194.145  -89339.91   -65816.65
  -85254.41   -67557.8    -50222.42   -88288.46   -80924.51   -65609.92
  -75229.85   -92069.26 ], shape=(32,), dtype=float32)
tf.Tensor(
[ -82766.95   -97640.41   -62512.562  -90434.87   -68457.695  -76954.414
 -127042.43   -72617.484  -56424.71   -63397.965  -98442.74   -70337.3
 -116980.734 -112895.17   -88298.125  -50682.305  -81030.766  -79713.78
  -75216.71   -76905.266 -100491.97   -57194.145  -89339.91   -65816.65
  -85254.41   -67557.8    -50222.42   -88288.46   -80924.51   -65609.92
  -75229.85   -92069.26 ], shape=(32,), dtype=float32)
tf.Tensor(
[ -99776.1   -109455.82   -69822.34  -103139.66   -77735.32   -92467.516
 -146044.14   -80753.336  -64805.36   -71757.66  -113611.625  -7

tf.Tensor(
[ -82148.22  -112583.92   -72099.875 -106155.89   -79672.09   -76532.37
 -126645.48   -83176.43   -77332.78   -63262.547  -98161.52   -70300.125
 -116820.7   -112077.734  -87723.9    -62714.43   -80780.05   -96449.21
  -74565.88   -76439.16  -100150.03   -61809.227 -140004.84   -80549.27
  -84805.42   -67142.164  -49920.387 -102194.39   -94625.484  -80850.836
  -74724.35   -91345.71 ], shape=(32,), dtype=float32)
tf.Tensor(
[ -97684.61  -123410.445  -78834.74  -117869.41   -88330.805  -90824.734
 -144275.75   -90569.01   -84899.875  -71054.39  -112272.71   -77456.61
 -131331.84  -133305.88  -107732.55   -71908.55   -90851.53  -108732.2
  -90096.16   -89671.5   -113977.625  -65281.09  -151946.61   -90961.734
 -104889.734  -84087.2    -59602.31  -112975.33  -104934.266  -86620.9
  -91605.875 -113754.836], shape=(32,), dtype=float32)
tf.Tensor(
[ -97684.61  -123410.445  -78834.74  -117869.41   -88330.805  -90824.734
 -144275.75   -90569.01   -84899.875  -71054.39  -112272.71   

KeyboardInterrupt: 

In [ ]:
a = tf.constant([[1.08,2.0,-3.0],[-4,0,-1]])
b = tf.math.sign(tf.math.sign(a)-1)+1
b