In [1]:
import tensorflow as tf
import tensorflow_probability as tfp
import numpy as np
import random
import time
from tensorflow import keras
from tensorflow.keras import layers
from tensorflow.keras import initializers
from tensorflow.keras import Model
from tensorflow.keras import models
from tensorflow.keras.layers import Dense, Conv2D, Dropout, Flatten, MaxPooling2D
from tensorflow.keras.models import Sequential
from sklearn.metrics import accuracy_score
import matplotlib.pyplot as plt

from sklearn.datasets import make_moons
from sklearn.model_selection import train_test_split

In [2]:
np.random.seed(0)
X, Y = make_moons(500, noise=0.1)

# Split into test and training data
x_train, x_test, y_train, y_test = train_test_split(X, Y, test_size=0.25, random_state=73)
y_train = np.reshape(y_train, (y_train.shape[0], 1))

train_ds = tf.data.Dataset.from_tensor_slices((x_train, y_train)).batch(4)

In [3]:
x_train

array([[ 4.82848133e-01, -1.43080488e-01],
       [ 1.75972079e+00, -2.87371541e-01],
       [-8.14458493e-01,  7.62518533e-01],
       [ 1.06481422e+00,  2.58995693e-01],
       [-5.73667899e-01,  8.42353755e-01],
       [ 6.63651392e-01, -2.97478430e-01],
       [-9.53676906e-01,  5.20094154e-01],
       [ 9.48396473e-01,  5.21015528e-01],
       [-7.91818361e-01,  3.84256392e-01],
       [ 6.58469258e-01,  8.56950250e-01],
       [ 2.65122170e-01,  3.11223906e-02],
       [ 9.37252340e-01,  1.30594361e-01],
       [ 5.56879662e-01,  9.46437763e-01],
       [ 8.69438590e-01,  4.30998937e-01],
       [ 1.91088695e+00,  2.32463234e-01],
       [-1.37565071e-01,  2.68130644e-01],
       [-1.61037237e-02,  9.79071019e-01],
       [ 1.85201319e+00,  1.94783543e-01],
       [ 1.38018265e-01,  9.72833442e-02],
       [ 9.14975328e-01,  2.47725841e-01],
       [-4.78494854e-01,  7.43201350e-01],
       [ 8.29738714e-01,  6.45517287e-01],
       [ 1.92143406e+00,  9.14885662e-02],
       [-9.

In [4]:
y_train

array([[1],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
    

In [5]:
train_ds

<BatchDataset shapes: ((None, 2), (None, 1)), types: (tf.float64, tf.int64)>

In [6]:
# Standard BP
model_bp = keras.Sequential(
    [
        keras.Input(shape=(2,)),
        layers.Dense(30, activation = "sigmoid"),
        layers.Dense(1, activation = "sigmoid")
    ]
)
model_bp.summary()
#model_bp.get_weights()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 30)                90        
_________________________________________________________________
dense_1 (Dense)              (None, 1)                 31        
Total params: 121
Trainable params: 121
Non-trainable params: 0
_________________________________________________________________


In [7]:
import time
batch_size = 4
epochs = 1700
opt = tf.keras.optimizers.SGD(learning_rate=0.1)

st = time.time()
model_bp.compile(loss="binary_crossentropy", optimizer=opt, metrics=["accuracy"])
model_bp.fit(x_train, y_train, batch_size=batch_size, epochs=epochs)
print(time.time() - st)

Train on 375 samples
Epoch 1/1700
375/375 [==============================] - 1s 4ms/sample - loss: 0.6231 - accuracy: 0.6747
Epoch 2/1700
375/375 [==============================] - 0s 690us/sample - loss: 0.4719 - accuracy: 0.8107
Epoch 3/1700
375/375 [==============================] - 0s 657us/sample - loss: 0.3961 - accuracy: 0.8187
Epoch 4/1700
375/375 [==============================] - 0s 728us/sample - loss: 0.3541 - accuracy: 0.8267
Epoch 5/1700
375/375 [==============================] - 0s 672us/sample - loss: 0.3261 - accuracy: 0.8293
Epoch 6/1700
375/375 [==============================] - 0s 703us/sample - loss: 0.3090 - accuracy: 0.8613
Epoch 7/1700
375/375 [==============================] - 0s 677us/sample - loss: 0.2934 - accuracy: 0.8693
Epoch 8/1700
375/375 [==============================] - 0s 1ms/sample - loss: 0.2783 - accuracy: 0.8720
Epoch 9/1700
375/375 [==============================] - 0s 808us/sample - loss: 0.2717 - accuracy: 0.8800
Epoch 10/1700
375/375 [======

In [8]:
model_bp.get_weights()

[array([[-11.479273  ,  -0.75434345,  -0.99506444,   0.8306037 ,
          -0.78342724,   0.6620247 ,   0.75992787,  -0.7881035 ,
           1.1026819 ,   0.76178944,   0.75856036,  -1.231669  ,
           0.78017163,  -1.8108716 ,  -0.8788251 ,   0.72974956,
           0.7426238 ,  -3.49158   ,  -0.7369801 ,   0.73370737,
          -1.060389  ,  -0.7787469 ,  -0.7448142 ,   0.7573035 ,
           0.7493385 ,  -1.1735576 ,   0.75740474,   0.9095993 ,
          -1.0232171 ,  -0.8337075 ],
        [ -7.658811  ,   0.470253  ,   0.7210488 ,  -0.54446757,
           0.329645  ,  -0.24077329,  -0.43451855,   0.3271214 ,
          -0.6507884 ,  -0.5094376 ,  -0.53083134,   0.61807865,
          -0.5254785 ,   0.90838677,   0.6970026 ,  -0.4182599 ,
          -0.51386935,   1.6600454 ,   0.42489663,  -0.5343992 ,
           0.75316423,   0.5846094 ,   0.55397046,  -0.43770903,
          -0.5155362 ,   0.7939532 ,  -0.54559654,  -0.56679606,
           0.7331984 ,   0.49213254]], dtype=float32

In [9]:
#hmc

def convert2_zero_one(x):
    
    t = tf.math.sigmoid(x)
    #t = tf.cast(tf.math.greater(samples[0], 0.5), tf.int32)
    
    return t

In [10]:
def rerange(x, r = 6.0):
    
    out_of_range = tf.cast(tf.math.greater(tf.math.abs(x), r), tf.float32)
    sign = tf.math.sign(x)
    
    return x * (1 - out_of_range) + sign * r * out_of_range

In [11]:
# MLP model
class StochasticMLP(Model):
    
    def __init__(self, hidden_layer_sizes=[100], n_outputs=10):
        super(StochasticMLP, self).__init__()
        self.hidden_layer_sizes = hidden_layer_sizes
        self.fc_layers = [Dense(layer_size) for layer_size in hidden_layer_sizes]
        self.output_layer = Dense(n_outputs)
    
    def call(self, x):
        
        #x = Flatten()(x)
        
        network = []
        
        for i, layer in enumerate(self.fc_layers):
            
            logits = layer(x)
            x = tfp.distributions.Bernoulli(logits=logits).sample()
            network.append(x)

        final_logits = self.output_layer(x) # initial the weight of output layer
            
        return network
    
    def target_log_prob(self, x, h, y):
        
        h_current = convert2_zero_one([tf.cast(h_i, dtype=tf.float32) for h_i in h])
        h_current = [h_current[0]]
        h_previous = [x] + h_current[:-1]
    
        nlog_prob = 0. # negative log probability
        
        for i, (cv, pv, layer) in enumerate(
            zip(h_current, h_previous, self.fc_layers)):
            
            ce = tf.nn.sigmoid_cross_entropy_with_logits(
                labels=cv, logits=layer(pv))
            
            nlog_prob += tf.reduce_sum(ce, axis = -1)
        
        fce = tf.nn.sigmoid_cross_entropy_with_logits(
            labels=tf.cast(y, tf.float32), logits=self.output_layer(h_current[-1]))
        nlog_prob += tf.reduce_sum(fce, axis = -1)
            
        return -1 * nlog_prob

    def target_log_prob2(self, x, h, y):

        h_current = convert2_zero_one(tf.split(h, self.hidden_layer_sizes, axis = 1))
        h_current = [h_current[0]]
        h_previous = [x] + h_current[:-1]
        
        nlog_prob = 0.
        
        for i, (cv, pv, layer) in enumerate(
            zip(h_current, h_previous, self.fc_layers)):
            
            ce = tf.nn.sigmoid_cross_entropy_with_logits(
                labels=cv, logits=layer(pv))
            
            nlog_prob += tf.reduce_sum(ce, axis = -1)
        
        fce = tf.nn.sigmoid_cross_entropy_with_logits(
            labels=tf.cast(y, tf.float32), logits=self.output_layer(h_current[-1]))
        nlog_prob += tf.reduce_sum(fce, axis = -1)
            
        return -1 * nlog_prob
    
    def generate_hmc_kernel(self, x, y, step_size = pow(1000, -1/4)):
        
        adaptive_hmc = tfp.mcmc.SimpleStepSizeAdaptation(tfp.mcmc.HamiltonianMonteCarlo(
            target_log_prob_fn = lambda v: self.target_log_prob2(x, v, y),
            num_leapfrog_steps = 2,
            step_size = step_size),
            num_adaptation_steps=int(100 * 0.8))
        
        return adaptive_hmc
    
    # new proposing-state method with HamiltonianMonteCarlo
    def propose_new_state_hamiltonian(self, x, h, y):
    
        h_current = h
        h_current = [tf.cast(h_i, dtype=tf.float32) for h_i in h_current]
        h_current = h_current[0]

        # initialize the HMC transition kernel
        
        adaptive_hmc = tfp.mcmc.SimpleStepSizeAdaptation(tfp.mcmc.HamiltonianMonteCarlo(
            target_log_prob_fn = lambda v: self.target_log_prob2(x, v, y),
            num_leapfrog_steps = 2,
            step_size = pow(1000, -1/4)),
            num_adaptation_steps=int(100*0.8))

        # run the chain (with burn-in)
        num_results = 1
        num_burnin_steps = 100

        samples = tfp.mcmc.sample_chain(
            num_results = num_results,
            num_burnin_steps = num_burnin_steps,
            current_state = h_current, # may need to be reshaped
            kernel = adaptive_hmc,
            trace_fn = None)

        h_new = tf.split(samples[0], self.hidden_layer_sizes, axis = 1)

        return(h_new)
    
    def update_weights(self, x, h, y, lr = 0.1):
        
        optimizer = tf.keras.optimizers.SGD(learning_rate = lr)
        with tf.GradientTape() as tape:
            loss = -1 * tf.reduce_mean(self.target_log_prob(x, h, y))
        
        grads = tape.gradient(loss, self.trainable_weights)
        optimizer.apply_gradients(zip(grads, self.trainable_weights))

    def get_predictions(self, x):

        logits = 0.0
        for layer in self.fc_layers:
            logits = layer(x)
            x = tf.math.sigmoid(logits)
        
        logits = self.output_layer(x)
        probs = tf.math.sigmoid(logits)
        #print(probs)
        labels = tf.cast(tf.math.greater(probs, 0.5), tf.int32)

        return labels

In [12]:
model = StochasticMLP(hidden_layer_sizes = [2], n_outputs=1)

In [13]:
network = [model.call(images) for images, labels in train_ds]
network


If you intended to run this layer in float32, you can safely ignore this warning. If in doubt, this warning is likely only an issue if you are porting a TensorFlow 1.X model to TensorFlow 2.

To change all layers to have dtype float64 by default, call `tf.keras.backend.set_floatx('float64')`. To change just this layer, pass dtype='float64' to the layer constructor. If you are the author of this layer, you can disable autocasting by passing autocast=False to the base Layer constructor.



[[<tf.Tensor: id=483497, shape=(4, 2), dtype=int32, numpy=
  array([[1, 0],
         [0, 1],
         [0, 0],
         [0, 1]], dtype=int32)>],
 [<tf.Tensor: id=483554, shape=(4, 2), dtype=int32, numpy=
  array([[0, 1],
         [1, 1],
         [0, 0],
         [0, 1]], dtype=int32)>],
 [<tf.Tensor: id=483589, shape=(4, 2), dtype=int32, numpy=
  array([[0, 0],
         [0, 1],
         [1, 1],
         [1, 0]], dtype=int32)>],
 [<tf.Tensor: id=483624, shape=(4, 2), dtype=int32, numpy=
  array([[0, 0],
         [1, 1],
         [1, 1],
         [0, 1]], dtype=int32)>],
 [<tf.Tensor: id=483659, shape=(4, 2), dtype=int32, numpy=
  array([[0, 1],
         [1, 1],
         [0, 1],
         [1, 1]], dtype=int32)>],
 [<tf.Tensor: id=483694, shape=(4, 2), dtype=int32, numpy=
  array([[0, 1],
         [0, 0],
         [1, 0],
         [0, 1]], dtype=int32)>],
 [<tf.Tensor: id=483729, shape=(4, 2), dtype=int32, numpy=
  array([[1, 1],
         [0, 1],
         [1, 0],
         [1, 1]], dtype=in

In [14]:
kernels = [model.generate_hmc_kernel(images, labels) for images, labels in train_ds]

In [ ]:
burnin = 1000
step_sizes = []
for i in range(burnin):
    
    network_new = []
    kernels_new = []
    
    for (images, labels), net, hmc_kernel in zip(train_ds, network, kernels):
        net_current = net
        net_current = [tf.cast(net_i, dtype=tf.float32) for net_i in net_current]
        net_current = net_current[0]
        
        num_results = 1
        num_burnin_steps = 0

        samples = tfp.mcmc.sample_chain(
            num_results = num_results,
            num_burnin_steps = num_burnin_steps,
            current_state = net_current, # may need to be reshaped
            kernel = hmc_kernel,
            #trace_fn = lambda _, pkr: pkr.inner_results.accepted_results.new_step_size,
            trace_fn = None,
            return_final_kernel_results = True)
        
        #print(samples[2].new_step_size.numpy())
        new_step_size = samples[2][4].numpy()
        step_sizes.append(new_step_size)
        
        new_state = rerange(samples[0][0])
        net_new = tf.split(new_state, [2], axis = 1)   
        network_new.append(net_new)
        
        # build new kernel
        ker_new = model.generate_hmc_kernel(images, labels, new_step_size)
        kernels_new.append(ker_new)
            
    network = network_new
    kernels = kernels_new
    
    #print(network[0])

In [ ]:
import matplotlib.pyplot as plt
plt.plot(np.arange(len(step_sizes)), step_sizes)
plt.show()

In [ ]:
print(network[0])

In [ ]:
epochs = 500

start_time = time.time()
for epoch in range(epochs):
    
    loss = 0.0
    acc = 0.0
    for bs, (images, labels) in enumerate(train_ds):
        
        # only one mini-batch
        model.update_weights(images, network[bs], labels, 0.1)
        #network_new = [model.propose_new_state_hamiltonian(images, net, labels) for (images, labels), net in 
        #               zip(train_ds, network)]
        
        network_new = []
        kernels_new = []
        for (images, labels), net, hmc_kernel in zip(train_ds, network, kernels):
            net_current = net
            net_current = [tf.cast(net_i, dtype=tf.float32) for net_i in net_current]
            net_current = net_current[0]
        
            num_results = 1
            num_burnin_steps = 0

            samples = tfp.mcmc.sample_chain(
                num_results = num_results,
                num_burnin_steps = num_burnin_steps,
                current_state = net_current, # may need to be reshaped
                kernel = hmc_kernel,
                trace_fn = None,
                return_final_kernel_results = True)
            
            new_state = rerange(samples[0][0])
            net_new = tf.split(new_state, [2], axis = 1)   
            network_new.append(net_new)
            
            ker_new = model.generate_hmc_kernel(images, labels, new_step_size)
            kernels_new.append(ker_new)
            
        network = network_new
        kernels = kernels_new
        
        loss += -1 * tf.reduce_mean(model.target_log_prob(images, network[bs], labels))
    
    preds = [model.get_predictions(images) for images, labels in train_ds]
    #print(preds)
    train_acc = accuracy_score(np.array(preds[0]), y_train)
    print("Epoch %d/%d: - %.4fs/step - loss: %.4f - accuracy: %.4f" 
          % (epoch + 1, epochs, (time.time() - start_time) / (epoch + 1), loss, train_acc))

In [ ]:
print(model.trainable_weights)

In [ ]:
model2 = StochasticMLP(hidden_layer_sizes = [30], n_outputs=1)
network2 = [model2.call(images) for images, labels in train_ds]
kernels2 = [model2.generate_hmc_kernel(images, labels) for images, labels in train_ds]